-- Insert Italy dive shops data
INSERT INTO diveshops (business_name, street_address, locale, country, region, website_url, phone, email, google_rating) VALUES
('Portofino Divers', 'Via Jacopo Ruffini 47, 16038 Santa Margherita Ligure (GE), Italy', 'Santa Margherita Ligure', 'Italy', 'Europe', 'https://portofinodivers.com/', '', 'info@portofinodivers.com', NULL),
('Diving Group Portofino', 'Via Favale 25, 16038 Santa Margherita Ligure (GE), Italy', 'Santa Margherita Ligure (Rapallo base nearby)', 'Italy', 'Europe', 'https://dgportofino.com/', '', 'info@dgportofino.com', NULL),
('DWS Diving', 'Via Favale 11, 16038 Santa Margherita Ligure (GE), Italy', 'Santa Margherita Ligure', 'Italy', 'Europe', 'https://www.dwsdiving.com/', '', 'info@dwsdiving.com', NULL),
('Centro Sub Tigullio', 'Via Luigi Cibrario 47/e, 16154 Genova (GE), Italy', 'Genova (Sestri Ponente)', 'Italy', 'Europe', 'https://www.cstigullio.com/', '', 'centrosubtigullio.ge@gmail.com', NULL),
('Tavolara Diving (Centro Sub Tavolara)', 'Via Molara 4/6, 07020 Porto San Paolo (OT), Italy', 'Porto San Paolo (OT)', 'Italy', 'Europe', 'https://www.tavolaradiving.it/', '', 'info@tavolaradiving.it', NULL),
('Nautilus Diving Center', 'Via Roma 14, 07020 Palau (SS), Italy', 'Palau (SS)', 'Italy', 'Europe', 'https://www.divesardegna.com/', '', 'info@divesardegna.com', NULL),
('Orso Diving Club', 'Loc. Poltu Quatu (lato ovest porto), 07021 Arzachena (OT), Italy', 'Arzachena (OT)', 'Italy', 'Europe', 'https://orsodiving.com/', '', 'info@orsodiving.com', NULL),
('Capo Galera Diving Center', 'Loc. Capo Galera, 07041 Alghero (SS), Italy', 'Alghero (SS)', 'Italy', 'Europe', 'https://www.capogalera.com/', '', 'capogalera@capogalera.com', NULL),
('Orca Diving Ustica', 'Via Cristoforo Colombo 39, 90051 Ustica (PA), Italy', 'Ustica (PA)', 'Italy', 'Europe', 'https://www.orcadivingustica.com/', '', 'info@orcadivingustica.com', NULL),
('Blue Diving Ustica', 'Piazza Vito Longo 4, 90051 Ustica (PA), Italy', 'Ustica (PA)', 'Italy', 'Europe', 'https://www.bluedivingustica.it/', '', 'info@bluedivingustica.it', NULL),
('DiveSicily Diving & Watersports', 'Naxos Harbor, 98035 Giardini Naxos (ME), Sicily, Italy', 'Giardini Naxos (ME)', 'Italy', 'Europe', 'https://www.divesicily.com/', '', 'info@divesicily.com', NULL),
('Jonio Pro-Dive Catania', 'c/o Camping Jonio, Via Villini a Mare 2, 95126 Catania (CT), Italy', 'Catania (CT)', 'Italy', 'Europe', 'https://jonioprodivecatania.com/', '', 'jonioprodivecatania@gmail.com', NULL),
('Centro Sub Campi Flegrei', 'Via Miliscola 165 (Lido Montenuovo), 80078 Pozzuoli (NA), Italy', 'Pozzuoli (NA)', 'Italy', 'Europe', 'https://www.centrosubcampiflegrei.it/', '', 'info@centrosubcampiflegrei.it', NULL),
('Punta Campanella Diving Sorrento', 'Via Marina Grande 186, 80067 Sorrento (NA), Italy', 'Sorrento (NA)', 'Italy', 'Europe', 'https://www.puntacampanelladiving.com/', '', 'info@puntacampanelladiving.com', NULL),
('ANS Diving Ischia', 'Via Girolamo Rocca 13, 80077 Ischia (NA), Italy', 'Ischia (NA)', 'Italy', 'Europe', 'https://ansdivingischia.it/', '', 'ansdivingischia@gmail.com', NULL),
('Aquanautic Elba', 'Loc. Morcone 33, 57031 Capoliveri (LI), Italy', 'Capoliveri (LI)', 'Italy', 'Europe', 'https://aquanautic-elba.de/', '', 'info@aquanautic-elba.de', NULL),
('Sub Now Diving Center (Marina di Campo)', 'Via Renato Fucini 452, 57034 Marina di Campo (LI), Italy', 'Marina di Campo (LI)', 'Italy', 'Europe', 'https://www.subnow.it/', '', 'info@subnow.it', NULL),
('Diving in Elba (Portoferraio)', 'Hotel Airone del Parco & delle Terme, 57037 Portoferraio (LI), Italy', 'Portoferraio (LI)', 'Italy', 'Europe', 'https://www.divinginelba.com/', '', 'info@divinginelba.com', NULL),
('Ponza Diving Center', 'Via Banchina, snc – 04027 Isola di Ponza (LT), Italy', 'Ponza', 'Italy', 'Europe', 'https://www.ponzadiving.com', '', 'info@ponzadiving.com', NULL),
('TropeaSub Diving Center', 'c/o Porto di Tropea, Molo Pescatori – 89861 Tropea (VV), Italy', 'Tropea', 'Italy', 'Europe', 'https://www.tropeasub.it', '', 'info@tropeasub.it', NULL),
('Megale Hellas Diving Center', 'Viale della Libertà, 23 – 89046 Marina di Gioiosa Ionica (RC), Italy', 'Marina di Gioiosa Ionica', 'Italy', 'Europe', 'https://www.megalehellasdiving.com', '', 'info@megalehellasdiving.com', NULL),
('Marlin Tremiti (San Domino)', 'Via A. Vespucci, snc – 71040 Isole Tremiti (FG), Italy', 'San Domino (FG)', 'Italy', 'Europe', 'https://www.marlintremiti.com', '', 'info@marlintremiti.com', NULL),
('Salento Diving', 'Porto Turistico di Santa Maria di Leuca, Molo A – 73040 Castrignano del Capo (LE), Italy', 'Santa Maria di Leuca (LE)', 'Italy', 'Europe', 'https://www.salentodiving.it', '', 'info@salentodiving.it', NULL),
('FRANMarine', 'Via del Porto, 2 – 86039 Termoli (CB), Italy', 'Termoli (CB)', 'Italy', 'Europe', 'https://www.franmarine-termoli.it', '', 'info@franmarine-termoli.it', NULL),
('Acquatica Scuba ASD (Pescara)', 'Via Torrente Piomba, 1 – 65015 Montesilvano (PE), Italy', 'Montesilvano (PE)', 'Italy', 'Europe', 'https://www.acquaticascuba.it', '', 'info@acquaticascuba.it', NULL),
('Centro Sub Monte Conero (Numana)', 'Via del Porto, 48 – 60026 Numana (AN), Italy', 'Numana (AN)', 'Italy', 'Europe', 'https://www.centrosubmonteconero.com', '', 'info@centrosubmonteconero.com', NULL),
('Dive Planet Rimini', 'Viale Ortigara, 59 – 47900 Rimini (RN), Italy', 'Rimini (RN)', 'Italy', 'Europe', 'https://diveplanet.org', '', 'info@diveplanet.org', NULL),
('Venice Diving (PADI IDC 5* Resort)', 'Camping Marina di Venezia & Camping Mediterraneo, 30013 Cavallino-Treporti (VE), Italy', 'Cavallino-Treporti / Venice', 'Italy', 'Europe', 'https://www.venicediving.com', '', 'info@venicediving.com', NULL),
('Sistiana Diving (Duino-Aurisina)', 'Località Sistiana, 1 – 34011 Duino-Aurisina (TS), Italy', 'Sistiana / Duino-Aurisina (TS)', 'Italy', 'Europe', 'https://www.sistianadiving.com', '', 'info@sistianadiving.com', NULL);
