-- Insert Thailand dive shops data
INSERT INTO diveshops (business_name, street_address, locale, country, region, website_url, phone, email, google_rating) VALUES
('Sea Bees Diving', '1/3 Moo 9, Viset Road, Chalong, Phuket 83130, Thailand', 'Phuket', 'Thailand', 'Asia', 'https://www.sea-bees.com/', '+66 76 381 765', 'info@sea-bees.com', NULL),
('All 4 Diving (Phuket)', '153/4 Rat Uthit 200 Pi Rd., Patong, Kathu, Phuket 83150, Thailand', 'Phuket', 'Thailand', 'Asia', 'https://www.all4divingphuket.com/', '+66 76 344 611', 'philippe@all4diving.com', NULL),
('Dive Asia (Phuket)', '23/6 Karon Road, Karon Beach, Phuket 83100, Thailand', 'Phuket', 'Thailand', 'Asia', 'https://www.diveasia.com/', '+66 76 330 598', '[email protected]', NULL),
('Local Dive Thailand', '95/13 Moo 7, Tambon Rawai, Amphur Muang, Phuket 83130, Thailand', 'Phuket', 'Thailand', 'Asia', 'https://localdivethailand.com/', '+66 80 696 1461; +66 62 018 0729', 'info@localdivethailand.com', NULL),
('Super Divers Phuket', '74/55 Nanai Road, Patong Beach, Phuket 83150, Thailand', 'Phuket', 'Thailand', 'Asia', 'https://www.superdiversphuket.com/', '+66 87 624 0674; +66 80 096 9684', 'superdiversphuket@gmail.com', NULL),
('Sea Fun Divers', 'c/o Le Méridien Phuket Beach Resort, Karon Noi Beach, Phuket 83100, Thailand', 'Phuket', 'Thailand', 'Asia', 'https://www.seafundivers.com/', '+66 81 367 4542', 'info@seafundivers.com', NULL),
('Phuket Dive Tours', '', 'Phuket', 'Thailand', 'Asia', 'https://www.phuketdivetours.com/', '+66 9 2679 2722; +66 87 022 5356', 'godivephuket@gmail.com', NULL),
('Khao Lak Scuba Adventures (Manta Queen Fleet)', '13/47 Moo 7, Khuk Khak, Takua Pa 82190, Phang Nga, Thailand', 'Khao Lak', 'Thailand', 'Asia', 'https://www.khaolakscubaadventures.com/', '+66 83 636 1010', 'contact@ksaliveaboard.com', NULL),
('Sea Dragon Dive Center', '5/51 Moo 7, Khuk Khak, Takua Pa, Phang Nga 82220, Thailand', 'Khao Lak', 'Thailand', 'Asia', 'https://www.seadragondivecenter.com/', '+66 83 176 5873', 'info@seadragondivecenter.com', NULL),
('Similan Diving Safaris', '9/16 Moo 7, Petchkasem Rd., Khuekkhak, Takua Pa, Phang Nga 82220, Thailand', 'Khao Lak', 'Thailand', 'Asia', 'https://www.similandivingsafaris.com/', '+66 76 485 470', 'info@similan-diving-safaris.com', NULL),
('Big Blue Diving Koh Tao', '14/148 Moo 1, Koh Tao, Surat Thani 84360, Thailand', 'Koh Tao', 'Thailand', 'Asia', 'https://www.bigbluediving.com/', '+66 77 456 415', 'info@bigbluediving.com', 5),
('Ban’s Diving Resort', 'Sairee Beach, Koh Tao 84360, Thailand', 'Koh Tao', 'Thailand', 'Asia', 'https://www.bansdivingresort.com/', '+66 77 456 466', 'info@bansdivingresort.com', NULL),
('Master Divers', '25/8 Moo 2, Mae Haad, Koh Tao 84360, Thailand', 'Koh Tao', 'Thailand', 'Asia', 'https://master-divers.com/', '+66 92 618 5637', 'info@master-divers.com', NULL),
('Sairee Cottage Diving', 'Sairee Beach, Koh Tao 84360, Thailand', 'Koh Tao', 'Thailand', 'Asia', 'https://www.saireecottagediving.com/', '+66 77 456 374', 'info@saireecottagediving.com', NULL),
('Roctopus Dive', '17 Moo 1, Koh Tao, Ko Pha-ngan District, Surat Thani 84360, Thailand', 'Koh Tao', 'Thailand', 'Asia', 'https://www.roctopusdive.com/', '+66 99 470 4566', 'info@roctopusdive.com', NULL),
('French Kiss Divers (Koh Tao)', '25/3 Moo 2, Mae Haad, Koh Tao, Surat Thani 84360, Thailand', 'Koh Tao', 'Thailand', 'Asia', 'https://frenchkissdiving.com/koh-tao-diving/', '+66 64 127 6082', 'frenchkissdivers@gmail.com', NULL),
('New Way Diving', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.newwaydiving.com/', '', '', NULL),
('Assava Dive Resort', '', 'Koh Tao', 'Thailand', 'Asia', 'https://assavadivers.com/', '', '', NULL),
('Scuba Junction', '', 'Koh Tao', 'Thailand', 'Asia', 'https://scubajunctiondiving.com/', '', '', NULL),
('Goodtime Adventures', '', 'Koh Tao', 'Thailand', 'Asia', 'https://goodtimeadventures.com/', '', '', NULL),
('Crystal Dive Koh Tao', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.crystaldive.com/', '', '', NULL),
('Simple Life Divers', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.simplelifedivers.com/', '', '', NULL),
('DJL Diving Koh Tao', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.djl-diving.com/', '', '', NULL),
('Lanta Diver', '259/2 Moo 3, Saladan, Koh Lanta, Krabi 81150, Thailand', 'Koh Lanta', 'Thailand', 'Asia', 'https://lantadiver.com/', '+66 87 891 4141', 'scuba@lantadiver.com', NULL),
('Blue Planet Divers (Lanta)', '150/1 Moo 1, Baan Saladan, Koh Lanta, Krabi 81150, Thailand', 'Koh Lanta', 'Thailand', 'Asia', 'https://www.blueplanetdivers.net/', '+66 85 472 3450', 'blueplanetdivers@gmail.com', NULL),
('Go Dive Lanta', '6 Moo 1, Saladan, Koh Lanta, Krabi 81150, Thailand', 'Koh Lanta', 'Thailand', 'Asia', 'https://godive-lanta.com/', '+66 81 892 8321', 'info@godive-lanta.com', NULL),
('Scubafish (Lanta)', '152-152/1, Moo 5, Ko Lanta Yai, Krabi 81150, Thailand', 'Koh Lanta', 'Thailand', 'Asia', 'https://www.scubafish.com/', '+66 83 175 3077; +66 75 665 095', 'contact@scubafish.com', NULL),
('Dive & Relax (Lanta)', '223 Moo 2, Saladan, Koh Lanta 81150, Thailand', 'Koh Lanta', 'Thailand', 'Asia', 'https://www.diveandrelax.com/', '+66 89 050 3009', 'info@diveandrelax.com', NULL),
('Kon‑Tiki Lanta', '', 'Koh Lanta', 'Thailand', 'Asia', 'https://www.kontiki-thailand.com/', '', '', NULL),
('Blue View Divers (Phi Phi)', '107 Moo 7, Phi Phi Island, Ao Nang, Amphur Muang, Krabi 81210, Thailand', 'Koh Phi Phi', 'Thailand', 'Asia', 'https://blueviewdivers.com/', '+66 92 512 5584', 'blueviewdivers@gmail.com', 5),
('Moskito Diving (Phi Phi)', '', 'Koh Phi Phi', 'Thailand', 'Asia', 'https://moskitodiving.com/', '', '', NULL),
('Island Divers (Phi Phi)', '', 'Koh Phi Phi', 'Thailand', 'Asia', 'https://www.islanddiverspp.com/', '', '', NULL),
('Phi Phi Scuba Diving Center', '', 'Koh Phi Phi', 'Thailand', 'Asia', 'https://phiphiscuba.com/', '', '', NULL),
('Seafari Dive Center (Pattaya)', '262 Mike Shopping Mall, Pattaya 2nd Road, Nong Prue, Bang Lamung, Chonburi 20150, Thailand', 'Pattaya', 'Thailand', 'Asia', 'https://www.seafari.co.th/', '+66 81 762 4187; +66 90 256 5174', 'diving@seafari.co.th', NULL),
('Mermaids Dive Center (Pattaya)', '315/166-167 Moo 12, Thappraya Road, Jomtien Beach, Pattaya 20150, Thailand', 'Pattaya', 'Thailand', 'Asia', 'https://www.mermaidsdivecenter.com/', '+66 38 303 333', 'dive@mermaidsdivecenter.com', NULL),
('Aquanauts Dive Centre (Pattaya)', '', 'Pattaya', 'Thailand', 'Asia', 'https://aquanautsdive.com/', '', '', NULL),
('Pattaya Dive Centre', '', 'Pattaya', 'Thailand', 'Asia', 'https://www.pattayadivecentre.com/', '', '', NULL),
('Jomtien Dive Center', '', 'Jomtien', 'Thailand', 'Asia', 'https://jomtiendivecenter.com/', '', '', NULL),
('The Dive Academy (Samui)', '157/15 Moo 1, Bophut, Koh Samui, Surat Thani 84320, Thailand', 'Koh Samui', 'Thailand', 'Asia', 'https://www.thediveacademysamui.com/', '+66 92 464 3264', 'info@thediveacademysamui.com', NULL),
('Discovery Divers (Samui)', '14/3 Moo 2, Bophut (Chaweng Beach), Koh Samui 84320, Thailand', 'Koh Samui', 'Thailand', 'Asia', 'https://discoverydivers.com/', '+66 95 271 0017; +66 84 056 6345', 'info@discoverydivers.com', NULL),
('100 Degrees East (Samui)', '', 'Koh Samui', 'Thailand', 'Asia', 'https://100degreeseast.com/', '', '', NULL),
('Sail Rock Divers (Phangan)', '15 Moo 7, Chaloklum, Koh Phangan 84280, Thailand', 'Koh Phangan', 'Thailand', 'Asia', 'https://www.sailrockdivers.com/', '+66 80 885 7268', 'sailrockphangan@gmail.com', NULL),
('Haad Yao Divers (Phangan)', '84/31 Moo 8, Koh Phangan, Surat Thani 84280, Thailand', 'Koh Phangan', 'Thailand', 'Asia', 'https://www.haadyaodivers.com/', '+66 84 841 2102; +66 83 135 6261', 'contact@haadyaodivers.com', NULL),
('Chaloklum Diving (Phangan)', '', 'Koh Phangan', 'Thailand', 'Asia', 'https://www.chaloklum-diving.com/', '', '', NULL),
('The Smiling Seahorse (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://thesmilingseahorse.com/', '', '', NULL),
('Deep Andaman Queen (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.deepandamanqueen.com/', '', '', NULL),
('The Junk & The Phinisi (Junk Liveaboards)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.junkliveaboards.com/', '', '', NULL),
('MV Giamani (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.giamani.com/', '', '', NULL),
('Aloha Ocean Adventures / Aloha Diving', '87/18 Moo 2, T. Rawai, A. Muang, Phuket 83130, Thailand', 'Phuket', 'Thailand', 'Asia', 'https://alohadiving.com/', '+66 97 924 3483', 'info@alohadiving.com', NULL),
('Siam Diving Enterprises (SDE)', '', 'Phuket', 'Thailand', 'Asia', 'https://www.siamdivingenterprises.com/', '', '', NULL),
('South Siam Divers (dayboats)', '459/1 The Best Villa, Patak Rd., Moo 3, Karon, Phuket 83100, Thailand', 'Phuket', 'Thailand', 'Asia', 'https://www.southsiam.com/', '+66 76 286 016', 'info@southsiamdivers.com', NULL),
('Andaman Scuba', '69/3 Moo 5, Petkasem Rd., Bang Niang Beach, Khao Lak 82220, Thailand', 'Phuket', 'Thailand', 'Asia', 'https://andaman-scuba.com/', '+66 88 444 6224', 'info@andamanscuba.com', NULL),
('Phuket Scuba Club', '', 'Phuket', 'Thailand', 'Asia', 'https://www.phuketscubaclub.com/', '', '', NULL),
('Merlin Divers', '74/3 Moo 3, Rim Had Rd., Kamala, Phuket 83150, Thailand', 'Phuket', 'Thailand', 'Asia', 'https://www.merlindivers.com/', '+66 76 385 518', 'info@phuket-diving-thailand.net', NULL),
('IQ-DIVE (Khao Lak)', '4/42 Moo 7, Khuk Khak, Takua Pa, Phang Nga 82220, Thailand', 'Khao Lak', 'Thailand', 'Asia', 'https://www.iq-divekhaolak.com/', '+66 76 485 614 / +66 81 891 2134', 'info@iq-dive.com', NULL),
('Big Blue Diving Khao Lak', '4/53 Moo 7, Khuk Kak, Takua Pa 82190, Phang Nga, Thailand', 'Khao Lak', 'Thailand', 'Asia', 'https://www.bigbluedivingkhaolak.com/', '+66 65 393 2289; +66 76 485 544', 'info@bigbluedivingkhaolak.com', NULL),
('Diving Khaolak (Diving Andaman)', '', 'Khao Lak', 'Thailand', 'Asia', 'https://www.divingkhaolak.com/', '', '', NULL),
('Similan Seven Sea Club', '80/14, Moo 5, Khuekkhak, Takua Pa, Phang-nga 82220, Thailand', 'Khao Lak', 'Thailand', 'Asia', 'https://www.similan-sea-club.com/', '+66 82 426 9797', 'info@similansevenseaclub.com', NULL),
('Mojo Divers', '15/3 Moo 1, Sairee Beach, Koh Tao 84360, Thailand', 'Koh Tao', 'Thailand', 'Asia', 'https://mojodiverskohtao.com/', '+66 77 456 710', 'info@mojodiverkohtao.com', NULL),
('Phoenix Divers Koh Tao', '', 'Koh Tao', 'Thailand', 'Asia', 'https://phoenixdiverskohtao.com/', '', '', NULL),
('Scuba Shack Koh Tao', '15/1 Moo 1, Sairee Beach, Koh Tao 84360, Thailand', 'Koh Tao', 'Thailand', 'Asia', 'https://scubashackkohtao.com/', '+66 84 344 7846', 'stefandivekohtao@gmail.com', NULL),
('Coral Grand Divers', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.coralgranddivers.com/', '', '', NULL),
('Buddha View Dive Resort', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.buddhaview-diving.com/', '', '', NULL),
('Sunshine Divers', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.sunshine-divers.com/', '', '', NULL),
('Phoenix Divers Koh Lanta', '', 'Koh Lanta', 'Thailand', 'Asia', 'https://www.phoenixdivers-kohlanta.com/', '', '', NULL),
('Hidden Depths Diving (Lanta)', '26 Moo 1, Ban Saladan, Koh Lanta, Krabi 81150, Thailand', 'Koh Lanta', 'Thailand', 'Asia', 'https://hiddendepthsdiving.com/', '+66 63 365 5757', 'info@hiddendepthsdiving.com', NULL),
('Palm Beach Divers (Lanta)', '', 'Koh Lanta', 'Thailand', 'Asia', 'https://palmbeachdivers.com/', '', '', NULL),
('Flip Flop Divers (Lanta)', '', 'Koh Lanta', 'Thailand', 'Asia', 'https://flipflopdivers.com/', '', '', NULL),
('Princess Divers (Phi Phi)', '103 Moo 7, T. Ao Nang, A. Muang, Krabi 81000, Thailand', 'Koh Phi Phi', 'Thailand', 'Asia', 'https://www.princessdiversthailand.com/', '+66 75 812 296', 'info@princessdivers.com', NULL),
('The Adventure Club (Phi Phi)', '125/19 Moo 7, Phi Phi Island, Krabi 81210, Thailand', 'Koh Phi Phi', 'Thailand', 'Asia', 'https://www.theadventureclub.com/', '+66 81 970 0314', 'info@adventureclubthailand.com', NULL),
('Blue View Divers (2nd listing URL)', '', 'Koh Phi Phi', 'Thailand', 'Asia', 'https://blueviewdivers.com/diving/', '', '', NULL),
('Real Divers (Pattaya)', '', 'Pattaya', 'Thailand', 'Asia', 'https://www.realdivepattaya.com/', '', '', NULL),
('Adventure Divers Pattaya', '', 'Pattaya', 'Thailand', 'Asia', 'https://www.adventurediverspattaya.com/', '', '', NULL),
('Dive Now (Pattaya)', '', 'Pattaya', 'Thailand', 'Asia', 'https://divenowpattaya.com/', '', '', NULL),
('Silent Divers (Samui)', '39 Chaweng Beach Rd, BoPhut, Koh Samui 84320, Thailand', 'Koh Samui', 'Thailand', 'Asia', 'https://silentdivers.com/', '+66 81 933 6641', 'bookings@silentdivers.com', NULL),
('Calypso Diving Koh Samui', '', 'Koh Samui', 'Thailand', 'Asia', 'https://www.calypso-diving.com/', '', '', NULL),
('Lotus Diving (Phangan)', '57/6 Moo 7, Chaloklum, Koh Phangan 84280, Surat Thani, Thailand', 'Koh Phangan', 'Thailand', 'Asia', 'https://lotusdiving.com/', '+66 77 374 142; +66 89 469 4719', 'info@lotusdiving.com', NULL),
('Asia Blue – Scuba (Phangan)', '', 'Koh Phangan', 'Thailand', 'Asia', 'https://www.asiablue.co/', '', '', NULL),
('Pirate Divers (Phangan)', '', 'Koh Phangan', 'Thailand', 'Asia', 'https://piratediversthailand.com/', '', '', NULL),
('MV Pawara (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.phuketdivetours.com/liveaboards/mv-pawara/', '', '', NULL),
('Sawasdee Fasai (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.phuketdivetours.com/liveaboards/sawasdee-fasai/', '', '', NULL),
('MV Dolphin Queen (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.khaolakexplorer.com/liveaboard/dolphin-queen/', '', '', NULL),
('MV Andaman (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.similandivingsafaris.com/mv-andaman/', '', '', NULL),
('Sunrise Divers (Phuket)', '', 'Phuket', 'Thailand', 'Asia', 'https://www.sunrise-divers.com/', '', '', NULL),
('Thailand Divers (Phuket)', '', 'Phuket', 'Thailand', 'Asia', 'https://thailand-divers.com/', '', '', 4.7),
('Sea Bees Khao Lak', '33/3 Moo 6, Petchkasem Road, Khuk Khak, Takua Pa, Phang Nga 82190, Thailand', 'Khao Lak', 'Thailand', 'Asia', 'https://www.sea-bees.com/dive-center/khao-lak/', '+66 76 485 174', 'officekl@sea-bees.com', NULL),
('Poseidon Dive Center Khao Lak', '', 'Khao Lak', 'Thailand', 'Asia', 'https://www.poseidon-khaolak.com/', '', '', NULL),
('Kon-Tiki Krabi', '873 Moo 2, Tambon Ao Nang, Amphur Muang, Krabi 81180, Thailand', 'Ao Nang', 'Thailand', 'Asia', 'https://www.kontiki-thailand.com/krabi/', '+66 98 014 1996', 'kontikikrabishop@gmail.com', NULL),
('Aqua Vision Krabi', '76/13 Moo 2, Ao Nang Beach, Ao Nang, Krabi 81180, Thailand', 'Ao Nang', 'Thailand', 'Asia', 'https://aqua-vision.net/', '+66 98 010 8589; +66 89 652 2474', 'contact@diving-krabi.com; info@aqua-vision.net', NULL),
('The Dive Ao Nang', '', 'Ao Nang', 'Thailand', 'Asia', 'https://thediveaonang.com/', '', '', NULL),
('Poseidon Diving Krabi', '', 'Ao Nang', 'Thailand', 'Asia', 'https://poseidonkrabi.com/', '', '', NULL),
('Blue Planet Divers – Tec & Rec', '', 'Koh Lanta', 'Thailand', 'Asia', 'https://www.blueplanetdivers.net/', '', '', NULL),
('Phoenix Divers Lanta (2nd listing)', '', 'Koh Lanta', 'Thailand', 'Asia', 'https://www.phoenixdivers-kohlanta.com/', '', '', NULL),
('Barakuda Phi Phi', '', 'Koh Phi Phi', 'Thailand', 'Asia', 'https://www.barakuda-diving.com/', '', '', NULL),
('Phi Phi Andaman Legacy Divers', '', 'Koh Phi Phi', 'Thailand', 'Asia', 'https://andamanlegacydivers.com/', '', '', NULL),
('Adang Sea Divers (Lipe)', '', 'Koh Lipe', 'Thailand', 'Asia', 'https://www.adangseadivers.com/', '', '', NULL),
('Forra Diving (Lipe)', '', 'Koh Lipe', 'Thailand', 'Asia', 'https://www.forradiving.com/', '', '', NULL),
('Castaway Divers (Lipe)', '', 'Koh Lipe', 'Thailand', 'Asia', 'https://www.castawaydivers.com/', '', '', NULL),
('Lipe Diving', '', 'Koh Lipe', 'Thailand', 'Asia', 'https://www.lipediving.com/', '', '', NULL),
('BB Divers (Koh Chang)', '', 'Koh Chang', 'Thailand', 'Asia', 'https://www.bbdivers.com/', '', '', NULL),
('ScubaDawgs (Koh Chang)', '', 'Koh Chang', 'Thailand', 'Asia', 'https://www.scubadawgs.com/', '', '', NULL),
('Dolphin Divers (Koh Chang)', '', 'Koh Chang', 'Thailand', 'Asia', 'https://www.dolphin-divers.com/', '', '', NULL),
('The Dive Adventure (Koh Chang)', '', 'Koh Chang', 'Thailand', 'Asia', 'https://www.the-dive-adventure.com/', '', '', NULL),
('Sea Robin Samui Divers', '', 'Koh Samui', 'Thailand', 'Asia', 'https://searobindivers.com/', '', '', NULL),
('Easy Divers Samui', '', 'Koh Samui', 'Thailand', 'Asia', 'https://www.easydivers-thailand.com/', '', '', NULL),
('Black Turtle Dive', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.blackturtledive.com/', '', '', NULL),
('New Heaven Dive School', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.newheavendiveschool.com/', '', '', NULL),
('Scuba Birds Koh Tao', '', 'Koh Tao', 'Thailand', 'Asia', 'https://scubabirds.com/thailand/koh-tao/', '', '', NULL),
('Sairee Hut Diving', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.saireehutdivers.com/', '', '', NULL),
('MV Oktavia (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://oktavia.net/', '', '', NULL),
('DiveRACE Class E (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.diverace.com/', '', '', 5),
('MV Hallelujah (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.liveaboardsasia.com/mv-hallelujah/', '', '', NULL),
('MV Lapat (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.khaolakexplorer.com/liveaboard/mv-lapat/', '', '', NULL),
('Aussie Divers Phuket', '', 'Phuket', 'Thailand', 'Asia', 'https://www.aussiediversphuket.com/', '', '', NULL),
('Kiwidivers Phuket', '', 'Phuket', 'Thailand', 'Asia', 'https://www.kiwidivers.com/', '', '', 5),
('West Coast Divers Phuket', '', 'Phuket', 'Thailand', 'Asia', 'https://westcoastdiversphuket.com/', '', '', NULL),
('SSS Phuket Diving', '', 'Phuket', 'Thailand', 'Asia', 'https://www.sssphuket.com/', '', '', NULL),
('Khao Lak Explorer', '', 'Khao Lak', 'Thailand', 'Asia', 'https://www.khaolakexplorer.com/', '', '', NULL),
('Wetzone Divers Khao Lak', '', 'Khao Lak', 'Thailand', 'Asia', 'https://www.wetzonedivers.com/', '', '', NULL),
('Sea Turtle Divers Khao Lak', '', 'Khao Lak', 'Thailand', 'Asia', 'https://www.seaturtledivers.com/', '', '', NULL),
('Scuba Addicts Krabi', '', 'Ao Nang', 'Thailand', 'Asia', 'https://www.scubaaddictskrabi.com/', '', '', NULL),
('Krabi Scuba Club', '', 'Ao Nang', 'Thailand', 'Asia', 'https://krabiscubaclub.com/', '', '', NULL),
('Koh Tao Divers', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.kohtaodivers.com/', '', '', NULL),
('Blue Immersion Koh Tao (Scuba)', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.blue-immersion.org/kohtaodiving/', '', '', NULL),
('Sairee Cottage Tech (scuba/tec)', '', 'Koh Tao', 'Thailand', 'Asia', 'https://www.saireecottagediving.com/tech/', '', '', NULL),
('Scandinavian Scuba Doo / Lanta Scuba', '', 'Koh Lanta', 'Thailand', 'Asia', 'https://lanta-scuba.com/', '', '', NULL),
('Dive Center Lanta', '', 'Koh Lanta', 'Thailand', 'Asia', 'https://www.divecenterlanta.com/', '', '', NULL),
('Phi Phi Barakuda (second brand page)', '', 'Koh Phi Phi', 'Thailand', 'Asia', 'https://barakuda-diving.com/en/phi-phi/', '', '', NULL),
('Phi Phi Sea Frog Divers', '', 'Koh Phi Phi', 'Thailand', 'Asia', 'https://seafrogdivers.com/', '', '', NULL),
('Ocean Pro Lipe', '', 'Koh Lipe', 'Thailand', 'Asia', 'https://oceanprolipe.com/', '', '', NULL),
('Koh Lipe Diving School', '', 'Koh Lipe', 'Thailand', 'Asia', 'https://kohlipedivingschool.com/', '', '', NULL),
('Scandinavian Chang Diving Center (SCDC)', '', 'Koh Chang', 'Thailand', 'Asia', 'https://scubadivingkohchang.com/', '', '', NULL),
('BB Divers Koh Mak', '', 'Koh Mak', 'Thailand', 'Asia', 'https://www.bbdivers.com/koh-mak/', '', '', NULL),
('BB Divers Koh Kood', '', 'Koh Kood', 'Thailand', 'Asia', 'https://www.bbdivers.com/koh-kood/', '', '', NULL),
('Sea Breeze Divers Samui', '', 'Koh Samui', 'Thailand', 'Asia', 'https://www.seabreezesamui.com/', '', '', NULL),
('Dream Team Divers (Phangan)', '', 'Koh Phangan', 'Thailand', 'Asia', 'https://www.dreamteamdivers.com/', '', '', NULL),
('MV Bavaria (Liveaboard)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.mvbavaria.de/', '', '', NULL),
('Giamani Liveaboard (alt site)', '', 'Khao Lak/Phuket', 'Thailand', 'Asia', 'https://www.thailand-liveaboards.com/mv-giamani/', '', '', NULL);