-- Insert Mexico dive shops data
INSERT INTO diveshops (business_name, street_address, locale, country, region, website_url, phone, email, google_rating) VALUES
('Cabo Pulmo Beach Resort – Dive Center', '', 'Cabo Pulmo', 'Mexico', 'North America', 'https://www.cabopulmo.com/', '', '', NULL),
('Cabo Pulmo Divers', '', 'Cabo Pulmo', 'Mexico', 'North America', 'https://cabopulmodivers.com/', '', '', NULL),
('Cabo Pulmo Diving', '', 'Cabo Pulmo', 'Mexico', 'North America', 'https://cabopulmodiving.com/', '', '', NULL),
('Cabo Pulmo Sport Center', '', 'Cabo Pulmo', 'Mexico', 'North America', 'https://www.cabopulmosportcenter.com/', '', '', NULL),
('Cabo Pulmo Watersports', '', 'Cabo Pulmo', 'Mexico', 'North America', 'https://cabopulmowatersports.com/', '', '', NULL),
('Cabo Adventures (Scuba)', '', 'Cabo San Lucas', 'Mexico', 'North America', 'https://www.cabo-adventures.com/en/tour/scuba-diving/', '', '', NULL),
('Cabo Private Guide (Scuba)', '', 'Cabo San Lucas', 'Mexico', 'North America', 'https://caboprivateguide.com/', '', '', NULL),
('Cabo Trek (Scuba)', '', 'Cabo San Lucas', 'Mexico', 'North America', 'https://cabowhalewatching.org/scuba-diving/', '', '', NULL),
('Dive Cabo', '', 'Cabo San Lucas', 'Mexico', 'North America', 'https://www.divecabo.com/', '', '', NULL),
('Dive Ninja Expeditions', '', 'Cabo San Lucas', 'Mexico', 'North America', 'https://www.diveninjaexpeditions.com/', '', '', NULL),
('Manta Scuba Diving', '', 'Cabo San Lucas', 'Mexico', 'North America', 'https://mantacabo.com/', '', '', NULL),
('Nautilus Dive Tech', '', 'Cabo San Lucas', 'Mexico', 'North America', 'https://nautilusdivetech.com/', '', '', NULL),
('Pisces Dive Shop', '', 'Cabo San Lucas', 'Mexico', 'North America', 'https://piscesdiveshop.com/', '', '', NULL),
('Baja Diving & Service', '', 'La Paz', 'Mexico', 'North America', 'https://bajadiving.com/', '', '', NULL),
('Baja Expeditions (Scuba)', '', 'La Paz', 'Mexico', 'North America', 'https://bajaex.com/', '', '', NULL),
('Club Cantamar – Dive Center', '', 'La Paz', 'Mexico', 'North America', 'https://clubcantamar.com/', '', '', NULL),
('Cortez Expeditions', '', 'La Paz', 'Mexico', 'North America', 'https://cortezexpeditions.com/', '', '', NULL),
('Dive in La Paz', '', 'La Paz', 'Mexico', 'North America', 'https://www.diveinlapaz.com/', '', '', NULL),
('Fun Baja', '', 'La Paz', 'Mexico', 'North America', 'https://www.funbaja.com/', '', '', NULL),
('La Paz Divers', '', 'La Paz', 'Mexico', 'North America', 'https://lapazdivers.com/', '', '', NULL),
('Sunrider Adventures (Scuba)', '', 'La Paz', 'Mexico', 'North America', 'https://sunrider.com.mx/', '', '', NULL),
('The Baja Adventure Co.', '', 'La Paz', 'Mexico', 'North America', 'https://thebajaadventureco.com/', '', '', NULL),
('The Cortez Club', '', 'La Paz', 'Mexico', 'North America', 'https://cortezclub.com/', '', '', NULL),
('Blue Nation Baja (Loreto)', '', 'Loreto', 'Mexico', 'North America', 'https://www.bluenationbaja.com/', '', '', NULL),
('Dolphin Dive Baja (Loreto)', '', 'Loreto', 'Mexico', 'North America', 'https://www.dolphindivebaja.com/', '', '', NULL),
('East Cape Explorers', 'Retorno Atun Sin Numero, Col. La Playita, Fte la Marina, San José del Cabo, 23403, Baja California Sur, Mexico', 'San José del Cabo', 'Mexico', 'North America', 'https://www.eastcapeexplorers.com/', '+52 624 242 6170', '', NULL),
('Natura Dive Manzanillo', '', 'Manzanillo', 'Mexico', 'North America', 'https://naturadive.com/', '', '', NULL),
('Dive Acapulco', '', 'Acapulco', 'Mexico', 'North America', 'https://diveacapulco.com.mx/', '', '', NULL),
('Carlo Scuba Diving Center', '', 'Zihuatanejo / Ixtapa', 'Mexico', 'North America', 'https://www.carloscuba.com/', '', '', NULL),
('Zihuatanejo Dive Center', '', 'Zihuatanejo / Ixtapa', 'Mexico', 'North America', 'https://zihuatanejodivecenter.com/', '', '', NULL),
('Banderas Scuba Republic', '', 'Puerto Vallarta', 'Mexico', 'North America', 'https://scubarepublic.com.mx/', '', '', NULL),
('Chico’s Dive Shop (PV)', '', 'Puerto Vallarta', 'Mexico', 'North America', 'https://www.chicosdiveshop.com/', '', '', NULL),
('Eco Divers Vallarta', '', 'Puerto Vallarta', 'Mexico', 'North America', 'https://www.ecodiversvallarta.com/', '', '', NULL),
('PADI Vallarta Adventures (Scuba)', '', 'Puerto Vallarta', 'Mexico', 'North America', 'https://www.vallarta-adventures.com/en/tour/scuba-diving', '', '', NULL),
('Pacific Scuba Vallarta', '', 'Puerto Vallarta', 'Mexico', 'North America', 'https://www.pacificscubavallarta.com/', '', '', NULL),
('Silent World Divers PV', '', 'Puerto Vallarta', 'Mexico', 'North America', 'https://silentworlddivers.com/', '', '', NULL),
('Vallarta Undersea', '', 'Puerto Vallarta', 'Mexico', 'North America', 'https://vallartaundersea.com/', '', '', NULL),
('Nautilus Liveaboards', '', 'Homeport: Cabo San Lucas', 'Mexico', 'North America', 'https://nautilusliveaboards.com/', '', '', NULL),
('MV Valentina (Fun Azul Fleet)', '', 'Homeport: La Paz/Cabo', 'Mexico', 'North America', 'https://www.fun-azulfleet.net/valentina/', '', '', NULL),
('Quino el Guardian Liveaboard', '', 'Homeport: Puerto Peñasco', 'Mexico', 'North America', 'https://www.quinoelguardian.com/', '', '', NULL),
('Rocio del Mar Liveaboard', '', 'Homeport: Puerto Peñasco/La Paz', 'Mexico', 'North America', 'https://www.rociodelmarliveaboard.com/', '', '', NULL),
('Punta Mita Expeditions (Scuba)', '', 'Punta Mita / La Cruz', 'Mexico', 'North America', 'https://puntamitaexpeditions.com/', '', '', NULL),
('Sayulita Entourage (Scuba)', '', 'Sayulita / Riviera Nayarit', 'Mexico', 'North America', 'https://www.sayulitaentourage.com/dive-center', '', '', NULL),
('Buceo Scuba Huatulco', '', 'Bahías de Huatulco', 'Mexico', 'North America', 'https://buceohuatulco.com/', '', '', NULL),
('Huatulco Dive Center', '', 'Bahías de Huatulco', 'Mexico', 'North America', 'https://www.huatulcodivecenter.com/', '', '', NULL),
('Hurricane Divers Huatulco', '', 'Bahías de Huatulco', 'Mexico', 'North America', 'https://hurricanedivers.com/', '', '', NULL),
('Big Wave Diving (Puerto Escondido)', '', 'Puerto Escondido', 'Mexico', 'North America', 'http://www.puertoescondidodivecentre.com', '', '', NULL),
('Deep Blue Dive Puerto Escondido', '', 'Puerto Escondido', 'Mexico', 'North America', 'https://www.deepbluedivemexico.com/', '', '', NULL),
('Akumal Dive Center', 'Carretera Cancún - Chetumal km 104, Akumal, Tulum, Quintana Roo, Mexico', 'Akumal', 'Mexico', 'North America', 'https://www.akumaldivecenter.com/', '+52 984 151 8775', 'dive@akumaldivecenter.com', NULL),
('Akumal Dive Shop', 'Akumal, Riviera Maya, Quintana Roo, Mexico', 'Akumal', 'Mexico', 'North America', 'https://akumaldiveshop.com/', '+52 984 875 9031; +52 984 310 6875', 'sales@akumaldiveshop.com', NULL),
('Blue Experience Diving (Akumal)', '', 'Akumal', 'Mexico', 'North America', 'https://blueexperiencediving.com/', '', '', NULL),
('Scuba Cancun', 'Kukulcán Blvd. Km 5, Zona Hotelera, Cancún, Quintana Roo, Mexico', 'Cancún', 'Mexico', 'North America', 'https://www.scubacancun.com.mx/', '+52 998 849 7508; +52 998 849 4736; +52 998 849 5226; +52 998 849 5225', '', NULL),
('Aquaworld (Scuba)', '', 'Cancún', 'Mexico', 'North America', 'https://aquaworld.com.mx/en/scuba-diving/', '', '', NULL),
('Cancun Diving Adventures', '', 'Cancún', 'Mexico', 'North America', 'https://www.cancundivingadventures.com/', '', '', NULL),
('Cancun Scuba Center', '', 'Cancún', 'Mexico', 'North America', 'https://cancunscubacenter.com/', '', '', NULL),
('Cancun Scuba Crew', '', 'Cancún', 'Mexico', 'North America', 'https://www.cancunscubacrew.com/', '', '', NULL),
('Coconut Divers', '', 'Cancún', 'Mexico', 'North America', 'https://coconutdivers.com/', '', '', NULL),
('Manta Divers Cancun', '', 'Cancún', 'Mexico', 'North America', 'https://mantadivers.com/', '', '', NULL),
('Scuba Total Cancun', '', 'Cancún', 'Mexico', 'North America', 'https://www.scubatotal.com/', '', '', NULL),
('Solo Buceo', '', 'Cancún', 'Mexico', 'North America', 'https://www.solobuceo.com/', '', '', NULL),
('Squalo Divers (Cancún)', '', 'Cancún', 'Mexico', 'North America', 'https://www.squalodivers.com/', '', '', NULL),
('Total Scuba Cancun', '', 'Cancún', 'Mexico', 'North America', 'https://totalscuba.com.mx/', '', '', NULL),
('Blue Angel Resort – Dive Shop', 'Carretera Costera Sur Km. 2.2, Cozumel, Quintana Roo, 77600, Mexico', 'Cozumel', 'Mexico', 'North America', 'https://www.blueangelresort.com/', '+52 987 876 6865', '', NULL),
('Cozumel Dive Academy', '', 'Cozumel', 'Mexico', 'North America', 'https://cozumeldiveacademy.com/', '', '', NULL),
('Dressel Divers (Cozumel)', '', 'Cozumel', 'Mexico', 'North America', 'https://www.dresseldivers.com/dive/mexico/cozumel-scuba-diving/', '', '', NULL),
('Pro Dive International (Occidental Cozumel)', '', 'Cozumel', 'Mexico', 'North America', 'https://www.prodiveinternational.com/dive-center/occidental/', '', '', NULL),
('Aldora Divers', 'Calle 5 Sur #37, Centro, 77600 Cozumel, Quintana Roo, Mexico', 'Cozumel', 'Mexico', 'North America', 'https://aldora.com/', '+52 987 872 3397', 'frontdesk@aldora.com', NULL),
('Aldora Villas Dive Center', '', 'Cozumel', 'Mexico', 'North America', 'https://aldora.com/', '', '', NULL),
('Aqua Safari Cozumel', '', 'Cozumel', 'Mexico', 'North America', 'https://www.aquasafari.com/', '', '', NULL),
('Blue Magic Scuba', 'Calle 4 Norte #71, Entre Rafael E. Melgar y 5a Av., 77600 Cozumel, Quintana Roo, Mexico', 'Cozumel', 'Mexico', 'North America', 'https://bluemagicscuba.com/', '+52 987 105 4418', 'godive@bluemagicscuba.com', NULL),
('Blue Project Cozumel', '', 'Cozumel', 'Mexico', 'North America', 'https://www.blueprojectcozumel.com/', '', '', NULL),
('Blue XT~Sea Diving', '', 'Cozumel', 'Mexico', 'North America', 'https://www.bluextseadiving.com/', '', '', NULL),
('Cozumel H2O', '', 'Cozumel', 'Mexico', 'North America', 'https://www.cozumelh2o.com/', '', '', NULL),
('Cozumel Marine World', '', 'Cozumel', 'Mexico', 'North America', 'https://cozumelmarineworld.com/', '', '', NULL),
('Cozumel Scuba Planet', '', 'Cozumel', 'Mexico', 'North America', 'https://www.cozumelscubaplanet.com/', '', '', NULL),
('Deep Blue Cozumel', '', 'Cozumel', 'Mexico', 'North America', 'https://deepbluecozumel.com/', '', '', NULL),
('Deep Exposure Advanced Dives', '', 'Cozumel', 'Mexico', 'North America', 'https://deepexposure.com/', '', '', NULL),
('Dive House Cozumel', '', 'Cozumel', 'Mexico', 'North America', 'https://www.divehouse.com/', '', '', NULL),
('Dive Palancar', '', 'Cozumel', 'Mexico', 'North America', 'https://www.divepalancar.com/', '', '', NULL),
('Dive Paradise', 'Kilometro 1.7, Carretera Costera Sur, across from Wyndham Cozumel Hotel & Resort, 77600 San Miguel de Cozumel, Quintana Roo, Mexico', 'Cozumel', 'Mexico', 'North America', 'https://diveparadise.com/', '+1 954 743 5310; +1 855 798 5300; +52 987 101 8585', 'reservations@diveparadise.com', NULL),
('Dive with Cristina', '', 'Cozumel', 'Mexico', 'North America', 'https://divewithcristina.com/', '', '', NULL),
('Dive with Martin', '', 'Cozumel', 'Mexico', 'North America', 'https://divewithmartin.com/', '', '', NULL),
('Liquid Blue Divers', '', 'Cozumel', 'Mexico', 'North America', 'https://liquidbluedivers.com/', '', '', NULL),
('Living Underwater', '', 'Cozumel', 'Mexico', 'North America', 'https://www.living-underwater.com/', '', '', NULL),
('Papa Hog’s Scuba Emporium', '', 'Cozumel', 'Mexico', 'North America', 'https://papahogs.com/', '', '', NULL),
('Salty Endeavors Cozumel Scuba', '', 'Cozumel', 'Mexico', 'North America', 'https://cozumelscuba.com/', '', '', NULL),
('Sand Dollar Sports (Scuba)', '', 'Cozumel', 'Mexico', 'North America', 'https://www.sanddollarsports.com/', '', '', NULL),
('Scuba Club Cozumel – Dive Op', '', 'Cozumel', 'Mexico', 'North America', 'https://www.scubaclubcozumel.com/', '', '', NULL),
('Scuba Du', '', 'Cozumel', 'Mexico', 'North America', 'https://www.scubadu.com/', '(987) 872-9505', 'scubadu@usa.net', NULL),
('Scuba Life Cozumel', '', 'Cozumel', 'Mexico', 'North America', 'https://scubalifecozumel.com/', '', '', NULL),
('Scuba Mau', '', 'Cozumel', 'Mexico', 'North America', 'https://scubamau.com/', '', '', NULL),
('Scuba Shack Cozumel', '', 'Cozumel', 'Mexico', 'North America', 'https://scubashackcoz.com/', '', '', NULL),
('Scuba with Alison', '', 'Cozumel', 'Mexico', 'North America', 'https://www.scubawithalison.com/', '', '', NULL),
('ScubaTony', '', 'Cozumel', 'Mexico', 'North America', 'https://scubatony.com/', '', 'info@scubatony.com', NULL),
('Tres Pelicanos', 'Calle 5 Sur entre Ave Rafael Melgar y 5th Ave #400B, Centro, 77600 San Miguel de Cozumel, Q.R., Mexico', 'Cozumel', 'Mexico', 'North America', 'https://trespelicanos.com/', '+52 987 869 1168', 'dive@trespelicanos.com', NULL),
('POCNA Dive Center (Isla Mujeres)', '', 'Isla Mujeres', 'Mexico', 'North America', 'https://www.pocnadivecenter.com/', '', '', NULL),
('Carey Dive Center', '', 'Isla Mujeres', 'Mexico', 'North America', 'https://www.careydiveonline.com/', '', '', NULL),
('DC Explorer Isla Mujeres', '', 'Isla Mujeres', 'Mexico', 'North America', 'https://www.dcexplorerislamujeres.com/', '', '', NULL),
('Gypsea Divers (Isla Mujeres)', '', 'Isla Mujeres', 'Mexico', 'North America', 'https://gypseadivers.com/', '', '', NULL),
('I Dive Isla Mujeres', '', 'Isla Mujeres', 'Mexico', 'North America', 'https://idiveislamujeres.com/', '', '', NULL),
('Mexico Divers', 'Av Francisco I. Madero SM1 M20 L10 Centro, Isla Mujeres, Quintana Roo, Mexico', 'Isla Mujeres', 'Mexico', 'North America', 'https://mexicodivers.com/', '+52 998 218 9216', 'info@mexicodivers.com', NULL),
('Sea Hawk Divers', '', 'Isla Mujeres', 'Mexico', 'North America', 'https://www.seahawkers.com/', '', '', NULL),
('Squalo Adventures', '', 'Isla Mujeres', 'Mexico', 'North America', 'https://squaloadventures.com/', '', '', NULL),
('Bucaneros Dive Centre', '', 'Mahahual', 'Mexico', 'North America', 'https://bucanerosdivecenter.com/', '', '', NULL),
('Costa Maya Reef Divers', '', 'Mahahual', 'Mexico', 'North America', 'https://www.costamayareefdivers.com/', '', '', NULL),
('Dreamtime Dive Center', '', 'Mahahual', 'Mexico', 'North America', 'https://www.dreamtimediving.com/', '', '', NULL),
('Aqua Excursions (Playa)', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://aquaexcursions.com.mx/', '', '', NULL),
('Blue Life', 'Calle 54 entre Av. 5ta y 1ra, Playa del Carmen, Quintana Roo, Mexico', 'Playa del Carmen', 'Mexico', 'North America', 'https://bluelife.com/', '+1 707 726 1122', 'info@bluelife.com', NULL),
('Dive Mike', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://www.divemike.com/', '', '', NULL),
('Diversity Diving', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://diversitydiving.com/', '', '', NULL),
('Dressel Divers (Playa del Carmen)', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://www.dresseldivers.com/destination/mexico/', '', '', NULL),
('Mexico Blue Dream', 'Calle 70, entre Av. 10 y 15, 77710 Playa del Carmen, Quintana Roo, Mexico', 'Playa del Carmen', 'Mexico', 'North America', 'https://mexicobluedream.com/', '+52 1 984 143 7400', 'info@mexicobluedream.com', NULL),
('Phocea Mexico (Playa)', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://myphocea.com/', '+52 984 134 6123', 'playa@myphocea.com', NULL),
('Playa Scuba Dive Center', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://www.playascuba.com/', '', '', NULL),
('Pro Dive International (Playa)', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://prodiveinternational.com/', '', '', NULL),
('ProTec Playa del Carmen', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://protecdiving.com/', '', '', NULL),
('Scuba Libre', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://www.scubalibre.com.mx/', '', '', NULL),
('Scuba Playa', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://www.scubaplaya.com/', '', '', NULL),
('ScubaCaribe (Playa del Carmen)', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://www.scubacaribe.com/diving/mexico/playa-del-carmen/', '', '', NULL),
('Tank-Ha Dive Center', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://tank-ha.com/', '', '', NULL),
('The Reef Marina (Playacar)', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://www.thereefmarina.com/divecenter/en/', '', '', NULL),
('Good Vibes Diving', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://goodvibesdiving.com/', '', '', NULL),
('Phantom Divers', '', 'Playa del Carmen', 'Mexico', 'North America', 'https://phantomdivers.com/', '', '', NULL),
('Planet Scuba Mexico', '', 'Puerto Aventuras', 'Mexico', 'North America', 'https://www.planetscubamexico.com/', '', '', NULL),
('Pro Dive International (Puerto Aventuras)', '', 'Puerto Aventuras', 'Mexico', 'North America', 'https://prodiveinternational.com/', '', '', NULL),
('Puerto Aventuras Water Sports', '', 'Puerto Aventuras', 'Mexico', 'North America', 'https://pawatersports.com/', '', '', NULL),
('Bahia Divers', '', 'Puerto Aventuras', 'Mexico', 'North America', 'https://bahia-divers.com/', '', '', NULL),
('Dive Aventuras', '', 'Puerto Aventuras', 'Mexico', 'North America', 'https://www.diveaventuras.com/', '', '', NULL),
('Fat Cat Dive Center', '', 'Puerto Aventuras', 'Mexico', 'North America', 'https://www.fatcatsail.com/diving', '', '', NULL),
('The Reef Marina (Puerto Aventuras)', '', 'Puerto Aventuras', 'Mexico', 'North America', 'https://thereefmarina.com/', '', '', NULL),
('Dive Puerto Morelos', '', 'Puerto Morelos', 'Mexico', 'North America', 'https://divepuertomorelos.com/', '', '', NULL),
('Dive With Ruben', 'Calle Adolfo López Mateos SM 2, Mz 2 Lote 2 (Hotel Arenas), Puerto Morelos, Quintana Roo', 'Puerto Morelos', 'Mexico', 'North America', 'https://scubapuertomorelos.com.mx/', '+52 998 130 3240', 'divewithruben@gmail.com', NULL),
('Wet Set Diving', 'Av. Javier Rojo Gomez, Lt. 16 Mz. 2, Smaz. 2, Fracc. Ojo de Agua, Puerto Morelos, Quintana Roo, 77580, Mexico', 'Puerto Morelos', 'Mexico', 'North America', 'https://www.wetset.com/', '+1 855 333 6222; +52 998 206 9204; WhatsApp +52 998 130 3988', 'info@wetset.com', NULL),
('ProTec Tulum', '', 'Tulum', 'Mexico', 'North America', 'https://protecdiving.com/', '', '', NULL),
('CenoteXperience', '', 'Tulum', 'Mexico', 'North America', 'https://www.cenotexperience.com/', '', '', NULL),
('Koox Diving', '10 Avenida Nte. 258, Gonzalo Guerrero, 77710 Playa del Carmen, Quintana Roo, Mexico (HQ listings vary by branch)', 'Tulum', 'Mexico', 'North America', 'https://kooxdiving.com/', '+52 1 984 141 5502', 'kooxdiving@gmail.com', NULL),
('Maya Blue Dive Center', '', 'Tulum', 'Mexico', 'North America', 'https://www.mayabluedivecenter.com/', '', '', NULL),
('Under The Jungle', '', 'Tulum', 'Mexico', 'North America', 'https://www.underthejungle.com/', '', '', NULL),
('Underworld Tulum', '', 'Tulum', 'Mexico', 'North America', 'https://underworldtulum.com/', '', 'lanny@underworldtulum.com', NULL),
('Costa de Cocos Dive Center', '', 'Xcalak', 'Mexico', 'North America', 'https://costadecocos.com/', '', '', NULL),
('Nomad Divers Xcalak', '', 'Xcalak', 'Mexico', 'North America', 'https://nomaddiversxcalak.com/', '', '', NULL),
('XTC Dive Center', '', 'Xcalak', 'Mexico', 'North America', 'https://www.xtcdivecenter.com/', '', '', NULL),
('Aqua Sports Center Mazatlán', '', 'Mazatlán', 'Mexico', 'North America', 'https://www.aquasports.mx/', '', '', NULL),
('Escualo Sports (Scuba)', '', 'Mazatlán', 'Mexico', 'North America', 'https://escualosports.com/', '', '', NULL),
('Mazatlán Scuba', '', 'Mazatlán', 'Mexico', 'North America', 'https://mazatlanscuba.com/', '', '', NULL),
('CocoAventura Buceo Veracruz', '', 'Veracruz', 'Mexico', 'North America', 'https://www.cocoaventura.com.mx/buceo/', '', '', NULL),
('Dorado Buceo Veracruz', '', 'Veracruz', 'Mexico', 'North America', 'http://www.doradobuceo.com/', '', '', NULL),
('Scubaver', '', 'Veracruz', 'Mexico', 'North America', 'https://www.scubaver.com/', '', '', NULL);