-- Insert Indonesia dive shops data
INSERT INTO diveshops (business_name, street_address, locale, country, region, website_url, phone, email, google_rating) VALUES
('Blue Season Bali', 'Jalan Danau Poso, Gang Wanasari 3b, Sanur 80228, Bali, Indonesia', 'Sanur', 'Indonesia', 'Asia', 'https://www.blueseasonbali.com/', '+62 811-3855-598 / +62 361 270 852', 'diving@blueseasonbali.com', NULL),
('Bali Scuba', '', 'Sanur', 'Indonesia', 'Asia', 'https://www.baliscuba.com/', '+62 818-0504-3888 (WhatsApp/SMS)', 'letsdive@baliscuba.com', NULL),
('Joe’s Gone Diving', 'Jl. By Pass Ngurah Rai 44A, Sanur, Denpasar 80228, Bali, Indonesia', 'Sanur', 'Indonesia', 'Asia', 'https://joesgonediving.com/', '+65 9760 0300', 'info@joesgonediving.com', NULL),
('Crystal Divers Bali', 'Jl By Pass Ngurah Rai, Gang Griya no 6, Sanur, Bali, Indonesia', 'Sanur', 'Indonesia', 'Asia', 'https://www.crystal-divers.com/', '+62 361 286737 / +62 811 386 8006 (WhatsApp)', 'info@crystal-divers.com', NULL),
('Atlantis Bali Diving (Dune)', 'Jl. By Pass Ngurah Rai No.96E, Sanur, Bali 80228, Indonesia', 'Sanur', 'Indonesia', 'Asia', 'https://atlantis-bali-diving.com/', '+62 361 284 131', 'info@dune-bali.com', NULL),
('AquaMarine Diving – Bali', 'Jalan Petitenget No.2A, Kuta, Bali 80361, Indonesia', 'Sanur', 'Indonesia', 'Asia', 'https://www.bali-diving.com/', '+62 361 4738 020', 'Info@AquaMarineDiving.com', NULL),
('World Diving Lembongan', 'Jalan Jungutbatu Raya, Nusa Lembongan, Bali, Indonesia', 'Nusa Lembongan', 'Indonesia', 'Asia', 'https://www.world-diving.com/', '+62 812-3900-686 (WhatsApp)', 'info@world-diving.com', NULL),
('Blue Corner Dive', 'Jungut Batu, Nusa Lembongan, Bali 80771, Indonesia', 'Nusa Lembongan', 'Indonesia', 'Asia', 'https://bluecornerdive.com/', '+62 812-3761-8151', 'info@bluecornerdive.com', NULL),
('Big Fish Diving', 'Secret Garden Bungalows, Jungutbatu Village, Nusa Lembongan, Indonesia', 'Nusa Lembongan', 'Indonesia', 'Asia', 'https://www.bigfishdiving.com/', '+62 813-5313-6861', 'info@bigfishdiving.com', NULL),
('Two Fish Divers – Nusa Lembongan', '', 'Nusa Lembongan', 'Indonesia', 'Asia', 'https://www.twofishdivers.com/locations/nusa-lembongan/', '+62 811-3811-4009', 'info@twofishdivers.com', NULL),
('Adventure Divers Bali', 'Jalan Jemeluk, Amed, Karangasem - Bali, Indonesia', 'Amed', 'Indonesia', 'Asia', 'https://adventurediversbali.com/', '+62 813-5313-6113 (WhatsApp)', 'adventurediversbali@gmail.com', NULL),
('Two Fish Divers – Amed', 'Jl. Raya Amed, Purwakerti, Abang, Karangasem 80852, Bali, Indonesia', 'Amed', 'Indonesia', 'Asia', 'https://www.twofishdivers.com/locations/amed/', '+62 813-4006-9321 / +62 811-3811-4009', 'bookings@twofishdivers.com', NULL),
('Bali Dive Trek (Tulamben)', 'Amed Br dinas Biaslantang, Desa Purwakerti, Kelod, Amed - Abang - Karangasem 80852, Bali, Indonesia', 'Tulamben', 'Indonesia', 'Asia', 'https://www.balidivetrek.com/', '+62 852-3838-9529', 'balidivetrek@gmail.com', NULL),
('Liberty Dive Resort (Dive Center)', 'Jalan Raya Amlapura–Singaraja, Desa Tulamben, Kubu, Karangasem 80853, Bali, Indonesia', 'Tulamben', 'Indonesia', 'Asia', 'https://www.libertydive.com/', '+62 363 23347; +62 813 3776 2206', 'libertydiveresort@gmail.com', NULL),
('Ocean Sun Dive Resort (Dive Center)', 'Jln. Raya Kubu Amlapura, Desa Tulamben, Karangasem 80853, Bali, Indonesia', 'Tulamben', 'Indonesia', 'Asia', 'https://www.oceansun-diveresort.com/', '+62 81 1336 4222; WhatsApp +62 81 33757 3434', 'info@ocean-sun.com', NULL),
('Tulamben Wreck Divers', '', 'Tulamben', 'Indonesia', 'Asia', 'https://www.tulambenwreckdivers.com/', '', '', NULL),
('Blue Marlin Komodo', 'Jalan Soekarno-Hatta, Labuan Bajo, Flores, NTT, Indonesia', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://www.bluemarlinkomodo.com/', '+62 811-1842-235', 'info@bluemarlinkomodo.com', NULL),
('Scuba Junkie Komodo', 'Komodo Beach Resort, Warloka, Flores, NTT, Indonesia', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://scubajunkiekomodo.com/', '+62 821-3790-8161', 'komodo@scubajunkie.com', NULL),
('Dive Komodo', 'Labuan Bajo 86554, Flores, NTT, Indonesia', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://divekomodo.com/', '+62 822-6611-7310 / +62 812-3763-4606', 'info@divekomodo.com', NULL),
('Manta Rhei', 'Jl. Soekarno Hatta No.16, Labuan Bajo, Flores, Indonesia', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://mantarhei.com/', '+62 821 4731 0340', 'info@mantarhei.com', NULL),
('Uber Scuba Komodo', 'Jl. Soekarno Hatta, Labuan Bajo, Flores, Indonesia 86554', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://uberscubakomodo.com/', '+62 813 3961 9724', 'dive@uberscubakomodo.com', NULL),
('Wunderpus Diving Komodo', '', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://wunderpusdiving.com/', '', '', NULL),
('Dragon Dive Komodo', '', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://www.dragondivekomodo.com/', '', '', NULL),
('Sea Dragon Komodo', '', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://seadragonkomodo.com/', '', '', NULL),
('Meridian Adventure Dive', '', 'Waisai (Waigeo)', 'Indonesia', 'Asia', 'https://www.meridianadventuredive.com/', '+62 821 9791 3807', 'reservations@meridianadventuredive.com', NULL),
('Papua Diving (Kri Eco/Sorido Bay)', '', 'Kri Island', 'Indonesia', 'Asia', 'https://www.papuadiving.com/', '+62 811 483 4614', 'info@papua-diving.com', NULL),
('Raja Ampat Biodiversity Resort (Dive Center)', '', 'Waigeo/Kri area', 'Indonesia', 'Asia', 'https://www.rajaampatbiodiversity.com/', '+62 812 4881 3677', 'info@rajaampatbiodiversity.com', NULL),
('Soul Scuba Divers Raja Ampat', 'Kri Island, Yenbuba, Meos Mansar, Raja Ampat 98472, Indonesia', 'Waisai (Waigeo)', 'Indonesia', 'Asia', 'https://www.soulscubadivers-rajaampat.com/', '+62 822 6614 5516', 'soulscubadivers@gmail.com', NULL),
('Manta Dive Gili Trawangan', '', 'Gili Trawangan', 'Indonesia', 'Asia', 'https://www.mantadive.com/', '+62 812 3788 9378', 'bookings@manta-dive.com', NULL),
('Blue Marlin Dive (Gili T)', '', 'Gili Trawangan', 'Indonesia', 'Asia', 'https://www.bluemarlindive.com/', '', '', NULL),
('Trawangan Dive', '', 'Gili Trawangan', 'Indonesia', 'Asia', 'https://www.trawangandive.com/', '', '', NULL),
('Gili Divers', '', 'Gili Trawangan', 'Indonesia', 'Asia', 'https://gili-divers.com/', '', '', NULL),
('Diversia Diving', '', 'Gili Trawangan', 'Indonesia', 'Asia', 'https://diversiaindonesia.com/', '', '', NULL),
('Manta Dive Gili Air', '', 'Gili Air', 'Indonesia', 'Asia', 'https://www.mantadive.com/gili-air/', '', '', NULL),
('Blue Marine Dive (Gili Air)', '', 'Gili Air', 'Indonesia', 'Asia', 'https://bluemarine-divers.com/', '', '', NULL),
('Blue Marlin Dive (Gili Meno)', '', 'Gili Meno', 'Indonesia', 'Asia', 'https://www.bluemarlindive.com/locations/gili-meno/', '', '', NULL),
('Blue Marlin Dive (Senggigi)', '', 'Senggigi', 'Indonesia', 'Asia', 'https://www.bluemarlindive.com/locations/lombok/', '', '', NULL),
('Scuba Froggy Lombok', '', 'Kuta Lombok', 'Indonesia', 'Asia', 'https://scubafroggy.com/', '', '', NULL),
('Dive Zone Lombok', '', 'Sekotong/Belongas Bay', 'Indonesia', 'Asia', 'https://www.dive-lombok.com/', '', '', NULL),
('Thalassa Dive Resorts', '', 'Manado', 'Indonesia', 'Asia', 'https://thalassa-dive.com/', '', '', NULL),
('Murex Dive (Manado/Bangka)', '', 'Manado', 'Indonesia', 'Asia', 'https://www.murexdive.com/', '', '', NULL),
('Two Fish Divers – Bunaken', '', 'Bunaken', 'Indonesia', 'Asia', 'https://www.twofishdivers.com/locations/bunaken/', '', '', NULL),
('NAD-Lembeh Resort (Dive Center)', '', 'Bitung (Lembeh)', 'Indonesia', 'Asia', 'https://www.nad-lembeh.com/', '', '', NULL),
('Critters at Lembeh / Lembeh Resort', '', 'Lembeh', 'Indonesia', 'Asia', 'https://www.lembehresort.com/', '', '', NULL),
('Siladen Resort & Spa (Dive Center)', '', 'Bunaken', 'Indonesia', 'Asia', 'https://www.siladen.com/', '', '', NULL),
('Alami Alor (Dive Resort)', '', 'Alor/Kalabahi', 'Indonesia', 'Asia', 'https://www.alamialor.com/', '', '', NULL),
('Alor Divers (Resort)', '', 'Pantar/Alor', 'Indonesia', 'Asia', 'https://www.alordivers.com/', '', '', NULL),
('Spice Island Divers (Ambon)', '', 'Ambon', 'Indonesia', 'Asia', 'https://spiceislanddivers.com/', '', '', NULL),
('Blue Motion Ambon', '', 'Ambon', 'Indonesia', 'Asia', 'https://bluemotiondive.com/destinations/ambon/', '', '', NULL),
('Scuba Junkie Sangalaki (Borneo)', '', 'Maratua', 'Indonesia', 'Asia', 'https://www.scubajunkieseas.org/borneo/', '', '', NULL),
('Maratua Paradise Resort (Dive Center)', '', 'Maratua', 'Indonesia', 'Asia', 'https://www.maratua-paradise.com/', '', '', NULL),
('Extra Divers (Nabucco/Maratua)', '', 'Nabucco/Maratua', 'Indonesia', 'Asia', 'https://www.extradivers-worldwide.com/', '', '', NULL),
('Wakatobi Dive Resort (Dive Center)', '', 'Tomia/Wakatobi', 'Indonesia', 'Asia', 'https://www.wakatobi.com/', '', '', NULL),
('Pelagian Liveaboard (Wakatobi)', '', 'Tomia/Wakatobi', 'Indonesia', 'Asia', 'https://www.wakatobi.com/pelagian-liveaboard/', '', '', NULL),
('Mermaid Liveaboards', '', 'Multiple (Bali/Komodo/Raja)', 'Indonesia', 'Asia', 'https://www.mermaid-liveaboards.com/', '', '', NULL),
('Damai Liveaboards', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://www.dive-damai.com/', '', '', NULL),
('Arenui Liveaboard', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://www.thearenui.com/', '', '', NULL),
('White/Blue Manta Liveaboards', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://www.whitemanta.com/', '', '', NULL),
('Indo Siren (Master Liveaboards)', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://www.masterliveaboards.com/indonesia/', '', '', NULL),
('SMY Ondina', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://www.smy-ondina.com/', '', '', NULL),
('MV Amira', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://www.diveamira.com/', '', '', NULL),
('Emperor Indonesia (Raja Laut)', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://www.emperordivers.com/liveaboards/indonesia.php', '', '', NULL),
('Geko Dive Bali', '', 'Padangbai', 'Indonesia', 'Asia', 'https://www.gekodivebali.com/', '', '', NULL),
('OK Divers Resort & Spa (Dive Center)', '', 'Padangbai', 'Indonesia', 'Asia', 'https://www.okdiversresort.com/', '', '', NULL),
('Absolute Scuba Bali (Padang Bai)', '', 'Padangbai', 'Indonesia', 'Asia', 'https://absolutescubabali.com/', '', '', NULL),
('Benthos Bali Dive Resort (Dive Center)', '', 'Candidasa', 'Indonesia', 'Asia', 'https://www.benthosbali.com/', '', '', NULL),
('Sea Rovers', '', 'Pemuteran', 'Indonesia', 'Asia', 'https://searovers.net/', '', '', NULL),
('Reef Seen Divers’ Resort', '', 'Pemuteran', 'Indonesia', 'Asia', 'https://www.reefseenbali.com/', '', '', NULL),
('Bali Diving Academy (Pemuteran)', '', 'Pemuteran', 'Indonesia', 'Asia', 'https://www.balibali-diving.com/bali-diving-academy-pemuteran/', '', '', NULL),
('Menjangan Dive Centre', '', 'Pemuteran', 'Indonesia', 'Asia', 'https://menjangandive.com/', '', '', NULL),
('Two Fish Divers – Nusa Penida', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://www.twofishdivers.com/locations/nusa-penida/', '', '', NULL),
('Warnakali Dive Center', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://www.warnakali.com/', '', '', NULL),
('Sanctum Dive Indonesia – Penida', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://sanctumdiveindonesia.com/nusa-penida/', '', '', NULL),
('Dive Concepts Penida', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://diveconcepts.com/nusa-penida', '', '', NULL),
('Abyss Dive Center Amed', '', 'Amed', 'Indonesia', 'Asia', 'https://www.abyssdivecenteramed.com/', '', '', NULL),
('Bali Reef Divers (Amed)', '', 'Amed', 'Indonesia', 'Asia', 'https://www.balireefdivers.com/', '', '', NULL),
('Maika Komodo Tour & Diving', '', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://www.maikakomdotour.com/diving/', '', '', NULL),
('Scuba Republic Komodo', '', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://www.scuba-republic.com/destinations/komodo/', '', '', NULL),
('Komodo Dive Center', '', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://www.komododivecenter.com/', '', '', NULL),
('Blue Magic Raja Ampat Dive Resort (Dive Center)', '', 'Waisai/Wasai', 'Indonesia', 'Asia', 'https://bluemagicrajaampat.com/', '', '', NULL),
('Waiwo Dive Resort (Dive Center)', '', 'Waisai', 'Indonesia', 'Asia', 'https://www.waiwodiverajaampat.com/', '', '', NULL),
('Raja Ampat Dive Lodge (Kri)', '', 'Kri Island', 'Indonesia', 'Asia', 'https://rajaampatdivelodge.com/', '', '', NULL),
('Arborek Dive Shop (Community)', '', 'Waigeo/Arborek', 'Indonesia', 'Asia', 'https://arborekdiveshop.com/', '', '', NULL),
('Oceans 5 Gili Air (chain listing; branch on Gili Air)', '', 'Gili Trawangan', 'Indonesia', 'Asia', 'https://www.oceans5dive.com/', '', '', NULL),
('Dive Central Gili', '', 'Gili Trawangan', 'Indonesia', 'Asia', 'https://www.divecentralgili.com/', '', '', NULL),
('3W Dive Gili Air', '', 'Gili Air', 'Indonesia', 'Asia', 'https://www.3wdive.com/', '', '', NULL),
('What Sup? Lombok Diving (Kuta)', '', 'Kuta Lombok', 'Indonesia', 'Asia', 'https://www.whatsuplombok.com/diving/', '', '', NULL),
('Belongas Bay Divers', '', 'Sekotong/Belongas Bay', 'Indonesia', 'Asia', 'https://www.belongasbay.com/', '', '', NULL),
('Eco Divers Manado', '', 'Manado', 'Indonesia', 'Asia', 'https://www.eco-divers.com/', '', '', NULL),
('Tasik Ria Resort – Sea Souls Dive Center', '', 'Manado', 'Indonesia', 'Asia', 'https://www.tasikria.com/dive/', '', '', NULL),
('Froggies Divers (Bunaken)', '', 'Bunaken', 'Indonesia', 'Asia', 'https://www.froggiesdiving.com/', '', '', NULL),
('Two Fish Divers – Lembeh', '', 'Lembeh', 'Indonesia', 'Asia', 'https://www.twofishdivers.com/locations/lembeh/', '', '', NULL),
('Dive Alor (Kalabahi)', '', 'Kalabahi/Alor', 'Indonesia', 'Asia', 'https://www.dive-alor.com/', '', '', NULL),
('Dive Into Ambon', '', 'Ambon', 'Indonesia', 'Asia', 'https://diveintoambon.com/', '', '', NULL),
('Blue Motion Banda', '', 'Banda Islands', 'Indonesia', 'Asia', 'https://bluemotiondive.com/destinations/banda/', '', '', NULL),
('Weda Reef & Rainforest Resort (Dive Center)', '', 'Weda Bay', 'Indonesia', 'Asia', 'https://wedaresort.com/', '', '', NULL),
('Derawan Dive Lodge (Scuba)', '', 'Derawan', 'Indonesia', 'Asia', 'https://www.scubajunkieseas.org/derawan-dive-lodge/', '', '', NULL),
('Nunukan Island Resort (Extra Divers)', '', 'Maratua', 'Indonesia', 'Asia', 'https://www.nunukan-island-resort.com/', '', '', NULL),
('Diving Indo', '', 'Sanur', 'Indonesia', 'Asia', 'https://www.diving-indo.com/', '', '', NULL),
('Bali Aqua Diving', '', 'Sanur', 'Indonesia', 'Asia', 'https://www.baliaquadive.com/', '', '', NULL),
('Nico Dives Cool', '', 'Sanur', 'Indonesia', 'Asia', 'https://www.nicodivescool.com/', '', '', NULL),
('Legend Diving Penida', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://www.legenddivingpenida.com/', '', '', NULL),
('Scuba Center Asia (Penida)', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://www.scubacenterasia.com/', '', '', NULL),
('Ceningan Divers', '', 'Nusa Ceningan', 'Indonesia', 'Asia', 'https://ceningandivers.com/', '', '', NULL),
('French Kiss Divers (Penida)', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://www.frenchkissdiving.com/nusa-penida/', '', '', NULL),
('Nomads Diving Penida', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://nomadsdive.com/', '', '', NULL),
('Tauch Terminal Tulamben', '', 'Tulamben', 'Indonesia', 'Asia', 'https://www.tauchterminal.com/', '', '', NULL),
('Amed Sea Explorers', '', 'Amed', 'Indonesia', 'Asia', 'https://www.amedseaexplorers.com/', '', '', NULL),
('Euro Dive Amed', '', 'Amed', 'Indonesia', 'Asia', 'https://eurodivebali.com/', '', '', NULL),
('Zen Dive Bali (Pemuteran)', '', 'Pemuteran', 'Indonesia', 'Asia', 'https://www.zendivebali.com/', '', '', NULL),
('Abyss Ocean World (Pemuteran)', '', 'Pemuteran', 'Indonesia', 'Asia', 'https://www.abyss-ocean-world.com/', '', '', NULL),
('Misool Resort (Dive Center)', '', 'Misool', 'Indonesia', 'Asia', 'https://www.misoolecoresort.com/', '', '', NULL),
('Raja Ampat Dive Resort (Waigeo)', '', 'Waigeo', 'Indonesia', 'Asia', 'https://www.rajaampatdiveresort.com/', '', '', NULL),
('Scuba Republic Raja Ampat', '', 'Waigeo/Kri area', 'Indonesia', 'Asia', 'https://www.scuba-republic.com/destinations/raja-ampat/', '', '', NULL),
('Oceans 5 Gili Air', '', 'Gili Air', 'Indonesia', 'Asia', 'https://www.oceans5dive.com/', '', '', NULL),
('Gili Air Divers', '', 'Gili Air', 'Indonesia', 'Asia', 'https://giliairdivers.com/', '', '', NULL),
('Living Colours Diving Bunaken', '', 'Bunaken', 'Indonesia', 'Asia', 'https://www.livingcolours.fi/', '', '', NULL),
('Blue Bay Divers (Bangka)', '', 'Bangka/Sahaung', 'Indonesia', 'Asia', 'https://www.bluebaydivers.de/en/', '', '', NULL),
('Black Sand Dive Retreat', '', 'Lembeh', 'Indonesia', 'Asia', 'https://www.blacksanddive.com/', '', '', NULL),
('YOS Dive Lembeh (Eco Beach)', '', 'Lembeh', 'Indonesia', 'Asia', 'https://www.yosdivelembeh.com/', '', '', NULL),
('Gangga Divers (Gangga Island Resort)', '', 'Gangga Island', 'Indonesia', 'Asia', 'https://www.ganggadivers.com/', '', '', NULL),
('La P’tite Kepa (Dive Center)', '', 'Kepa Island / Alor', 'Indonesia', 'Asia', 'https://www.laptitekepa.com/', '', '', NULL),
('La Galigo Liveaboard', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://www.lagaligoliveaboard.com/', '', '', NULL),
('Samambaia Liveaboard', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://www.samambaiacruises.com/', '', '', NULL),
('Tiaré Cruise', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://www.tiarecruise.com/', '', '', NULL),
('Adelaar Liveaboard', '', 'Multiple (Bali/Komodo)', 'Indonesia', 'Asia', 'https://www.adelaar-cruises.com/', '', '', NULL),
('Wallacea Dive Cruises (Ambai/Seahorse)', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://wallacea-divecruises.com/', '', '', NULL),
('Bali Diving Academy (Sanur)', '', 'Sanur', 'Indonesia', 'Asia', 'https://www.balibali-diving.com/', '', '', NULL),
('Dune Bali (Atlantis) – Sanur', 'Jl. By Pass Ngurah Rai No.96E, Sanur, Bali 80228, Indonesia', 'Sanur', 'Indonesia', 'Asia', 'https://atlantis-bali-diving.com/', '+62 361 284 131', 'info@dune-bali.com', NULL),
('Scuba Junkie Penida', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://scubajunkiepenida.com/', '', '', NULL),
('Newbro Dive Nusa Penida', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://www.newbrodive.com/', '', '', NULL),
('DPM Diving Bali (Penida)', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://dpmdiving.com/destination/bali-nusa-penida/', '', '', NULL),
('Water WorxX Dive Center Amed', '', 'Amed', 'Indonesia', 'Asia', 'https://waterworxx.com/', '', '', NULL),
('Adventure Divers Bali (Amed)', '', 'Amed', 'Indonesia', 'Asia', 'https://adventurediversbali.com/', '', '', NULL),
('Baruna Divers Padang Bai', '', 'Padangbai', 'Indonesia', 'Asia', 'https://barunadivers.com/', '', '', NULL),
('Manta Dive Gili Meno', '', 'Gili Meno', 'Indonesia', 'Asia', 'https://www.mantadive.com/gili-meno/', '', '', NULL),
('Divine Divers Gili Meno', '', 'Gili Meno', 'Indonesia', 'Asia', 'https://www.divinedivers.com/', '', '', NULL),
('DSM Dive Gili Trawangan', '', 'Gili Trawangan', 'Indonesia', 'Asia', 'https://www.dsm-dive.com/', '', '', NULL),
('Odyssea Divers Sekotong (at Cocotinos)', '', 'Sekotong/Secret Gilis', 'Indonesia', 'Asia', 'https://odysseadivers.com/sekotong/', '', '', NULL),
('Flores XP Adventure Diving', '', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://www.floresxp-adventure.com/komodo-diving/', '', '', NULL),
('Red Whale Komodo', '', 'Labuan Bajo', 'Indonesia', 'Asia', 'https://redwhalekomodo.com/', '', '', NULL),
('Bunaken Oasis Dive Resort (Dive Center)', '', 'Bunaken', 'Indonesia', 'Asia', 'https://www.bunakenoasis.com/', '', '', NULL),
('Eco Divers Lembeh (White Sands)', '', 'Lembeh', 'Indonesia', 'Asia', 'https://www.eco-divers.com/lembeh-white-sands/', '', '', NULL),
('Coral Eye Bangka (Dive Center)', '', 'Bangka Island', 'Indonesia', 'Asia', 'https://www.coral-eye.com/', '', '', NULL),
('Divers Lodge Lembeh', '', 'Lembeh', 'Indonesia', 'Asia', 'https://www.diverslodgelembeh.com/', '', '', NULL),
('Bira Dive Camp', '', 'Bira', 'Indonesia', 'Asia', 'https://biradivecamp.com/', '', '', NULL),
('Blue Planet Dive Bira', '', 'Bira', 'Indonesia', 'Asia', 'https://www.blueplanetdiversbira.com/', '', '', NULL),
('Black Marlin Dive (Togian)', '', 'Kadidiri', 'Indonesia', 'Asia', 'https://www.blackmarlindive.com/', '', '', NULL),
('Kadidiri Paradise (Dive Center)', '', 'Kadidiri', 'Indonesia', 'Asia', 'https://www.kadidiriparadise.com/', '', '', NULL),
('Triton Bay Divers', '', 'Kaimana', 'Indonesia', 'Asia', 'https://www.tritonbaydivers.com/', '', '', NULL),
('Nabucco Island Resort (Extra Divers)', '', 'Nabucco/Maratua', 'Indonesia', 'Asia', 'https://www.extradivers-worldwide.com/en/dive-centers/indonesia/nabucco-island-resort/', '', '', NULL),
('Carpe Diem Phinisi', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://www.carpediem-phinisi.com/', '', '', NULL),
('Prana by Atzaro', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://pranabyatzaro.com/', '', '', NULL),
('Bali Diving Academy (Lembongan)', '', 'Nusa Lembongan', 'Indonesia', 'Asia', 'https://www.balibali-diving.com/bali-diving-academy-nusa-lembongan/', '', '', NULL),
('Bali Hai Diving Adventures', '', 'Nusa Lembongan', 'Indonesia', 'Asia', 'https://www.balihaidiving.com/', '', '', NULL),
('Nomads Diving Penida (2nd listing)', '', 'Nusa Penida', 'Indonesia', 'Asia', 'https://nomadsdive.com/', '', '', NULL),
('Tulamben Dive Center', '', 'Tulamben', 'Indonesia', 'Asia', 'https://tulambendive.com/', '', '', NULL),
('Dive Concepts – Tulamben', '', 'Tulamben', 'Indonesia', 'Asia', 'https://diveconcepts.com/tulamben', '', '', NULL),
('Dive Concepts – Amed', '', 'Amed', 'Indonesia', 'Asia', 'https://diveconcepts.com/amed', '', '', NULL),
('LumbaLumba Diving Manado', '', 'Manado', 'Indonesia', 'Asia', 'https://www.lumbalumbadiving.com/', '', '', NULL),
('Bastianos Dive Resort – Bunaken (Dive Center)', '', 'Bunaken', 'Indonesia', 'Asia', 'https://www.bastianos.com/bunaken/', '', '', NULL),
('Bastianos Dive Resort – Lembeh (Dive Center)', '', 'Lembeh', 'Indonesia', 'Asia', 'https://www.bastianos.com/lembeh/', '', '', NULL),
('Cha Cha Nature Resort (Dive Center)', '', 'Bunaken', 'Indonesia', 'Asia', 'https://chacha-bunaken.com/', '', '', NULL),
('Papua Explorers (Dive Center)', '', 'Waigeo', 'Indonesia', 'Asia', 'https://www.papuaexplorers.com/', '', '', NULL),
('Cove Eco Resort (Dive Center)', '', 'Yeben/Cove area', 'Indonesia', 'Asia', 'https://www.coveecoresort.com/', '', '', NULL),
('Sanctum Una Una (Dive Resort)', '', 'Una Una', 'Indonesia', 'Asia', 'https://sanctumdiveindonesia.com/una-una/', '', '', NULL),
('Seven Seas Indonesia', '', 'Multiple (Komodo/Raja/Banda)', 'Indonesia', 'Asia', 'https://thesevenseas.net/', '', '', NULL),
('Sea Safari Cruises (Sea Safari VII etc.)', '', 'Multiple (Raja/Banda/Komodo)', 'Indonesia', 'Asia', 'https://www.seasafaricruises.com/', '', '', NULL),
('Pindito Liveaboard', '', 'Multiple (Raja/Banda/Komodo)', 'Indonesia', 'Asia', 'https://www.pindito.com/', '', '', NULL),
('Wisesa Liveaboard', '', 'Multiple (Raja/Banda/Komodo)', 'Indonesia', 'Asia', 'https://wisesa-liveaboard.com/', '', '', NULL),
('Calico Jack Liveaboard', '', 'Multiple (Raja/Banda/Komodo)', 'Indonesia', 'Asia', 'https://www.calicojackcharters.com/', '', '', NULL),
('El Aleph Yacht (scuba charters)', '', 'Multiple (Raja/Banda/Komodo)', 'Indonesia', 'Asia', 'https://www.elaleph.com/', '', '', NULL),
('Euphoria Liveaboard', '', 'Multiple (Raja/Banda/Komodo)', 'Indonesia', 'Asia', 'https://www.euphoria-liveaboard.com/', '', '', NULL);