-- Insert France dive shops data
INSERT INTO diveshops (business_name, street_address, locale, country, region, website_url, phone, email, google_rating) VALUES
('H2JO Diving', '19 Quai des Cabestans, 56640 Arzon, France', 'Arzon (Morbihan)', 'France', 'Europe', 'https://h2jo.bzh', '+33 2 97 53 62 73', 'contact@h2jo.fr', NULL),
('Abysse Plongée', 'Port du Moulin Blanc, 29200 Brest, France', 'Brest', 'France', 'Europe', 'http://www.abysseplongee.fr', '+33 2 98 02 32 68', 'abysseplongeebrest@gmail.com', NULL),
('Arimair Plongée', '8 Rue de Kerfautras, 29200 Brest, France', 'Brest', 'France', 'Europe', 'https://arimair.fr', '+33 2 98 46 67 75', 'ecole.plongee@arimair.fr', NULL),
('Centre de plongée Éric Sauvage', '49 Avenue Alain Le Lay, 29900 Concarneau', 'Concarneau', 'France', 'Europe', 'https://eric-sauvage.com', '', 'contact@eric-sauvage.com', NULL),
('ISA Plongée Crozon', '18 rue de Reims, 29160 Crozon', 'Crozon', 'France', 'Europe', 'https://www.isacrozon.fr', '', 'centre.isa@gmail.com', NULL),
('Émeraude Plongée', '1 Place du Québec, 35400 Saint-Malo, France', 'Saint-Malo', 'France', 'Europe', 'https://www.emeraudeplongee.fr', '+33 2 99 20 16 90', 'contact@emeraudeplongee.fr', NULL),
('Haliotis Plongée', 'Port de Portivy, 56510 Saint-Pierre-Quiberon', 'Saint-Pierre-Quiberon (Morbihan)', 'France', 'Europe', 'https://haliotisplongee.com', '', 'contact@haliotisplongee.com', NULL),
('Armor Plongée', '1F rue de l’Étache, 22440 Ploufragan (base at Saint‑Quay‑Portrieux)', 'Saint-Quay-Portrieux (Côtes-d’Armor)', 'France', 'Europe', 'https://www.armorplongee.com', '', 'contact@armorplongee.com', NULL),
('CAP Trébeurden (Centre Activités Plongée)', 'Port de Plaisance, 22560 Trébeurden', 'Trébeurden', 'France', 'Europe', 'https://cap-trebeurden.com', '', 'infocap@cap-trebeurden.com', NULL),
('Isula Plongée', 'Plage de l’Hôtel Cala di Sole, Route des Sanguinaires, 20000 Ajaccio, France', 'Ajaccio', 'France', 'Europe', 'https://www.isula-plongee.com', '+33 4 95 52 06 39', 'isula-plongee@orange.fr', NULL),
('Club de Plongée Bastiais', 'Port de Toga, 20200 Bastia', 'Bastia', 'France', 'Europe', 'https://www.plongee-bastia.com/', '', 'clubdeplongeebastiais@gmail.com', NULL),
('Corsica Sub (Bastia)', 'Quai de la Madonetta, 20200 Bastia', 'Bastia', 'France', 'Europe', 'https://www.corsica-sub.fr/', '', 'contact@corsica-sub.fr', NULL),
('Toga Plongée', 'Port de Toga, 20200 Bastia', 'Bastia (Haute-Corse)', 'France', 'Europe', 'https://www.togaplongee.com', '', 'togaplongee@orange.fr', NULL),
('Diving Calvi A Piaghja', 'Route de la Pinède, 20260 Calvi', 'Calvi (Haute-Corse)', 'France', 'Europe', 'https://www.divingcalvi.fr', '', 'divingcalvi@icloud.com', 4.9),
('Porto-Vecchio Plongée', 'Rue Mansuetus Alessandri, 20137 Porto-Vecchio, France', 'Porto-Vecchio', 'France', 'Europe', 'https://portovecchioplongee.fr', '+33 6 71 86 82 67', 'contact@portovecchioplongee.fr', NULL),
('Actisub Plongée', 'Quai de l’Aliso (port), 20217 Saint‑Florent; Adresse postale : Lieu‑dit Corsu, 20232 Oletta', 'Saint-Florent (Haute-Corse)', 'France', 'Europe', 'https://www.actisub.com', '', 'actisub@yahoo.fr', NULL),
('Abbeville Plongée Scub''Abb', '4 place Clemenceau, 80100 Abbeville', 'Abbeville', 'France', 'Europe', 'https://www.scubabb.fr/', '', 'abbevilleplongee@gmail.com', NULL),
('CSMCO (Club Sous-Marin de la Côte d’Opale)', 'Quai Chanzy, Port de Plaisance, 62200 Boulogne-sur-Mer', 'Boulogne-sur-Mer', 'France', 'Europe', 'https://associations.boulogne-sur-mer.fr/associations/club-sous-marin-de-la-cote-dopale/', '', 'csmco.president@orange.fr', NULL),
('CPESMDE (Club Plongée Exploration Sous-Marine Dunkerque)', '2567 route de l’écluse Wattier, 59140 Dunkerque', 'Dunkerque', 'France', 'Europe', 'https://www.dunkerque-plongee.fr/', '', 'dunkerque.plongee@laposte.net', NULL),
('YCPAC (Yacht Club Plongée Arromanches Courseulles)', 'Courseulles-sur-Mer, 14470 (local associatif)', 'Arromanches / Courseulles-sur-Mer', 'France', 'Europe', 'https://arromanches-plongees-epaves.fr', '', 'renseignementplongeeycpac@gmail.com', NULL),
('Pôle Plongée Normandie', 'Port Chantereyne, 50100 Cherbourg-en-Cotentin, France', 'Cherbourg-en-Cotentin', 'France', 'Europe', 'https://www.poleplongee.fr', '+33 2 33 41 21 21', 'contact@poleplongee.fr', NULL),
('CSSMD (Club des Sports Sous-Marins Dieppois)', '43 avenue Vauban, 76200 Dieppe', 'Dieppe', 'France', 'Europe', 'https://www.cssmd.fr/', '', 'plongee.cssmd@outlook.fr', NULL),
('CSH Granville-Chausey (Club Subaquatique Hippocampe)', '478 avenue de l''Europe, 50400 Yquelon', 'Granville', 'France', 'Europe', 'https://granville.jeplonge.org/', '', 'communication-granville@jeplonge.org', NULL),
('EPPE – École de Plongée Paul Éluard', '3632 quai du Rhône (club) / 89 rue Florimont-Laurent (pool), Le Havre', 'Le Havre (Seine-Maritime)', 'France', 'Europe', 'https://lh-plongee-eppe.fr', '', 'eppe_plongee@live.fr', NULL),
('Caen-Ouistreham Plongée', 'Ouistreham Riva-Bella (local du club)', 'Ouistreham', 'France', 'Europe', 'http://www.caen-ouistreham-plongee.org/', '', 'infos@caen-ouistreham-plongee.org', NULL),
('Club de Plongée Arcachonnais (CPA)', 'Quai Goslar, 33120 Arcachon', 'Arcachon (Gironde)', 'France', 'Europe', 'https://club-de-plongee-arcachonnais.pepsup.com', '', 'cplongeearcachon@gmail.com', NULL),
('BAB Subaquatique', '1A Allée Port des Pêcheurs, 64200 Biarritz, France', 'Biarritz', 'France', 'Europe', 'https://www.babsubaquatique.fr', '+33 6 09 26 22 65', 'contact@babsubaquatique.fr', NULL),
('Les Aquanautes', 'Quai Notre Dame, 40130 Capbreton', 'Capbreton', 'France', 'Europe', 'https://www.les-aquanautes.com', '', 'Lesaquanautes@yahoo.fr', NULL),
('Spot Plongée', 'ZA des 2 Pins, 6 rue de Pourguedeuil, 40130 Capbreton', 'Capbreton', 'France', 'Europe', 'https://spotplongee.fr', '', 'info@spotplongee.fr', NULL),
('Odyssée Bleue Socoa', '4 Chemin des Blocs, 64500 Ciboure, France', 'Ciboure (Socoa)', 'France', 'Europe', 'https://odysseebleuesocoa.fr', '+33 6 63 54 13 63', 'odysseebleuesocoa@live.fr', NULL),
('PLANET OCEAN DIVE CENTER', '8 Rue des Orangers, 64700 Hendaye, France', 'Hendaye', 'France', 'Europe', 'https://planetocean.fr', '+33 6 62 63 66 27', 'contact@planetocean.fr', NULL),
('URPEAN Espace Plongée', '10 Rue des Orangers (Quai de Floride), 64700 Hendaye, France', 'Hendaye', 'France', 'Europe', 'https://www.urpean.com', '+33 6 88 74 68 69', 'info@urpean.com', NULL),
('Subaqua Club La Rochelle', 'Rue Léonce Maillot, 17000 La Rochelle', 'La Rochelle (Charente-Maritime)', 'France', 'Europe', 'https://subaqua17.com', '', 'secretariat@subaqua17.com', NULL),
('Oléron Plongée – Les Joyeux Corsaires', '125 Rue de la Pointe de Chaucre, 17190 Saint-Georges-d’Oléron, France', 'Saint-Georges-d’Oléron', 'France', 'Europe', 'https://www.oleronplongee17.fr', '+33 6 95 45 60 14; +33 6 89 42 15 84', 'ecoleplongee@oleronplongee17.fr; plonger17@oleronplongee17.fr', NULL),
('Rédéris Plongée', 'Quai de la République, 66650 Banyuls-sur-Mer, France', 'Banyuls-sur-Mer', 'France', 'Europe', 'https://www.rederis.com', '+33 4 68 88 31 66', 'contact@rederis.com', NULL),
('Abyss Plongée Cap d’Agde', '21 impasse du Globe – Le Pharo, 34300 Cap d’Agde', 'Cap d’Agde (Hérault)', 'France', 'Europe', 'https://www.abyssplongee.com', '', 'abyssplongee34@gmail.com', NULL),
('Cap Cerbère', 'Route d’Espagne, 66290 Cerbère, France', 'Cerbère', 'France', 'Europe', 'https://www.plongee-cap-cerbere.com', '+33 4 68 88 41 00', 'capcerbere@gmail.com', NULL),
('Bulles Plongée Palavas', '23 Route de Maguelone, 34250 Palavas-les-Flots', 'Palavas-les-Flots (Hérault)', 'France', 'Europe', 'https://www.bullesplongee.com', '', 'info@bullesplongee.com', NULL),
('Leucate Plongée', '2037 Avenue du Rec de l’Entrée, 11370 Port-Leucate, France', 'Port-Leucate', 'France', 'Europe', 'https://www.leucateplongee.fr', '+33 6 86 13 09 22', 'info@leucateplongee.fr', NULL),
('CNT Plongée (Cercle Nautique Turballais)', 'Derrière la Capitainerie, Port de Plaisance, 44420 La Turballe', 'La Turballe', 'France', 'Europe', 'https://cntplongee.fr', '', 'cnt.laturballe@gmail.com', NULL),
('Immersion Plongée 85', '691 Bd de l''Île Vertime, Ponton du Vendée Globe, 85100 Les Sables-d’Olonne', 'Les Sables-d’Olonne', 'France', 'Europe', 'https://www.immersionplongee85.com', '', 'immersionplongee85@hotmail.com', NULL),
('Cooleur Plongée', 'Place du Lehn (Bâtiment SNSM), 44420 Piriac-sur-Mer', 'Piriac-sur-Mer', 'France', 'Europe', 'https://www.cooleurplongee-bateauecole.com', '', 'cooleur-plongee@orange.fr', NULL),
('Easy Dive Cannes', '2 Rue Esprit Violet, 06400 Cannes, France', 'Cannes', 'France', 'Europe', 'https://www.easy-dive.com', '+33 4 93 43 40 42', 'easydive@easydive.fr', NULL),
('Plongée Club de Cannes', '34 Boulevard Montfleury, 06400 Cannes, France (base at Quai Saint-Pierre)', 'Cannes', 'France', 'Europe', 'https://www.plongee-cannes.com', '+33 6 12 58 10 86', 'info@plongee-cannes.com', NULL),
('O2 Plongée', 'Port de Carqueiranne, 83320 Carqueiranne, France', 'Carqueiranne', 'France', 'Europe', 'https://o2plongee.fr', '+33 7 70 90 40 58', 'contact@o2plongee.fr', NULL),
('Narval Plongée', '11 Avenue de la Viguerie, 13260 Cassis, France', 'Cassis', 'France', 'Europe', 'https://www.narval-plongee.fr', '+33 4 42 01 87 59', 'fabienne2k6@narval-plongee.fr', NULL),
('Diamond Diving', '11 Rue des Pêcheurs, Port Camille Rayon, 06220 Golfe-Juan, France', 'Golfe-Juan (Vallauris)', 'France', 'Europe', 'https://www.diamonddiving.net', '+33 6 15 30 52 23', 'info@diamonddiving.net', NULL),
('Ulysse Plongée', 'Presqu’île de Giens, Port de la Madrague, 83400 Hyères', 'Hyères (Var)', 'France', 'Europe', 'https://www.ulysseplongee.fr', '', 'ulysseplongee@gmail.com', NULL),
('Aqualonde Plongée', '22 Place de l’Hélice, Carré du Port Miramar, 83250 La Londe-les-Maures', 'La Londe-les-Maures (Var)', 'France', 'Europe', 'https://aqualonde-plongee.com', '', 'contact@aqualonde-plongee.com', NULL),
('DUNE La Londe', 'Place de l’Hélice – Carré du Port, 83250 La Londe-les-Maures', 'La Londe-les-Maures (Var)', 'France', 'Europe', 'https://france.dune-world.com/fr/llm/contact', '', 'lalonde@dune-world.com', NULL),
('La Cigale Plongée', 'Avenue Henry Clews, Port La Napoule, 06210 Mandelieu-La Napoule, France', 'Mandelieu-La Napoule', 'France', 'Europe', 'https://www.lacigale-plongee.com', '+33 6 29 09 87 92', 'info@lacigale-plongee.com', NULL),
('DUNE Marseille', '7 Port de la Pointe Rouge, 13008 Marseille', 'Marseille (Bouches-du-Rhône)', 'France', 'Europe', 'https://france.dune-world.com/en/mrs/contact', '', 'marseille@dune-world.com', 4.8),
('Aquadomia', 'Base DUNE Marseille, 7 Port de la Pointe Rouge, 13008 Marseille, France', 'Marseille (Pointe Rouge)', 'France', 'Europe', 'https://www.aquadomia.com', '+33 4 13 33 38 00', 'contact@aquadomia.com', NULL),
('Atoll Plongée (Marseille Plongée)', '31 Traverse Prat, 13008 Marseille, France', 'Marseille (Pointe Rouge)', 'France', 'Europe', 'https://www.atollplongee.com', '+33 4 91 72 18 14', 'marseilleplongee@gmail.com', NULL),
('L’Atelier de la Mer', 'Port de la Pointe Rouge – Entrée n°2, 13008 Marseille, France', 'Marseille (Pointe Rouge)', 'France', 'Europe', 'https://atelierdelamer.com', '+33 4 91 72 54 12', 'info@atelierdelamer.com', NULL),
('CIP Nice', '2 Ruelle des Moulins, 06000 Nice, France', 'Nice', 'France', 'Europe', 'https://www.cip-nice.com', '+33 4 93 55 59 50', 'info@cip-nice.com', NULL),
('Le Poséidon - Centre École de Plongée & Snorkeling', 'Quai Lunel / Quai A. Infernet, Port de Nice, 06300 Nice', 'Nice', 'France', 'Europe', 'https://poseidon-nice.com', '', 'tlo@poseidon-nice.com', NULL),
('Nice Diving', '13 Quai des Deux Emmanuels, 06300 Nice, France', 'Nice', 'France', 'Europe', 'https://www.nicediving.com', '+33 6 14 46 04 06', 'nicediving@gmail.com', NULL),
('Club Sous l’Eau', 'Port Santa Lucia, 83700 Saint-Raphaël', 'Saint-Raphaël (Var)', 'France', 'Europe', 'https://clubsousleau.fr', '', 'contact@clubsousleau.fr', NULL),
('Euro Plongée', '2170 Route de la Corniche, 83700 Saint-Raphaël', 'Saint-Raphaël (Var)', 'France', 'Europe', 'https://europlongee.fr', '', 'contact@europlongee.fr', NULL),
('Sanary Plongée', '2 Quai Wilson, 83110 Sanary-sur-Mer', 'Sanary-sur-Mer (Var)', 'France', 'Europe', 'https://sanaryplongee.com', '', 'contact@sanary-plongee.com', NULL),
('Toulon Plongée', '125 Quai des Sous-mariniers, 83000 Toulon, France', 'Toulon', 'France', 'Europe', 'https://www.toulonplongee.com', '+33 6 34 67 54 70', 'toulonplongee@gmail.com', NULL);